// ===== CBAM 完整产品数据库 =====
// 数据来源：CBAM商品清单.xlsx
const cbamProductDB = [
    {c:"25070080",n:"其他高岭土（未煅烧的除外）",e:"Other kaolinic clays except non-calcined kaolinic clays"},
    {c:"25231000",n:"水泥熟料",e:"Cement clinkers"},
    {c:"25232100",n:"白色硅酸盐水泥，不论是否人工着色",e:"White portland cement, whether or not artificially coloured"},
    {c:"25232900",n:"其他硅酸盐水泥（不包括白水泥，无论是否人工着色）",e:"Portland cement (excl. white, whether or not artificially co"},
    {c:"25233000",n:"高铝水泥",e:"Aluminous cement"},
    {c:"25239000",n:"其他水凝水泥，不论是否着色（不包括硅酸盐水泥和高铝水泥）",e:"Cement, whether or not coloured (excl. portland cement and a"},
    {c:"26011200",n:"已烧结铁矿砂及其精矿（焙烧黄铁矿除外）",e:"Agglomerated iron ores and concentrates (excl. roasted iron "},
    {c:"27160000",n:"电力",e:"Electrical energy"},
    {c:"28041000",n:"氢",e:"Hydrogen"},
    {c:"28080000",n:"硝酸；磺硝酸",e:"Nitric acid; sulphonitric acids"},
    {c:"28141000",n:"无水氨",e:"Anhydrous ammonia"},
    {c:"28142000",n:"氨水",e:"Ammonia in aqueous solution"},
    {c:"28342100",n:"硝酸钾",e:"Nitrate of potassium"},
    {c:"31021012",n:"尿素水溶液，按干品重量计含氮量＞45%，且按重量计尿素含量≥31.8% 但≤33.2%（不包括毛重≤10 千克包装的产品",e:"Urea in aqueous solution, containing >45% nitrogen in relati"},
    {c:"31021015",n:"尿素水溶液，按干品重量计含氮量＞45%，且按重量计尿素含量＞33.2% 但≤55%（不包括毛重≤10 千克包装的产品）",e:"Urea in aqueous solution, containing >45% nitrogen in relati"},
    {c:"31021019",n:"尿素（无论是否为水溶液），按干品重量计含氮量＞45%（不包括呈片剂或类似形态的产品、毛重≤10 千克包装的产品，或按重量",e:"Urea, whether or not in aqueous solution, containing >45% ni"},
    {c:"31021090",n:"尿素（无论是否为水溶液），按干无水品重量计含氮量≤45%（不包括本章中呈片剂或类似形态的产品，或毛重≤10 千克包装的产",e:"Urea, whether or not in aqueous solution, containing <= 45% "},
    {c:"31022100",n:"硫酸铵（不包括呈片剂或类似形态的产品，或毛重≤10 千克包装的产品）",e:"Ammonium sulphate (excl. that in tablets or similar forms, o"},
    {c:"31022900",n:"硫酸铵与硝酸铵的复盐及混合物（不包括本章中呈片剂或类似形态的产品，或毛重≤10 千克包装的产品）",e:"Double salts and mixtures of ammonium sulphate and ammonium "},
    {c:"31023010",n:"硝酸铵水溶液（不包括毛重≤10 千克包装的产品）",e:"Ammonium nitrate in aqueous solution (excl. that in packages"},
    {c:"31023090",n:"硝酸铵（不包括水溶液形态、呈片剂或类似形态的产品，或毛重≤10 千克包装的产品）",e:"Ammonium nitrate (excl. that in aqueous solution, in tablets"},
    {c:"31024010",n:"硝酸铵与碳酸钙或其他无效肥及无机物的混合物，用作肥料，按重量计含氮量≤28%（不包括呈片剂或类似形态的产品，或毛重≤10",e:"Mixtures of ammonium nitrate with calcium carbonate or other"},
    {c:"31024090",n:"硝酸铵与碳酸钙或其他无效肥及无机物的混合物，用作肥料，按重量计含氮量＞28%（不包括呈片剂或类似形态的产品，或毛重≤10",e:"Mixtures of ammonium nitrate with calcium carbonate or other"},
    {c:"31025000",n:"硝酸钠（不包括呈片剂或类似形态的产品，或毛重≤10 千克包装的产品）",e:"Sodium nitrate (excl. that in tablets or similar forms, or i"},
    {c:"31026000",n:"硝酸钙与硝酸铵的复盐及混合物（不包括呈片剂或类似形态的产品，或毛重≤10 千克包装的产品）",e:"Double salts and mixtures of calcium nitrate and ammonium ni"},
    {c:"31028000",n:"尿素与硝酸铵的水溶液或氨溶液混合物（不包括毛重≤10 千克包装的产品）",e:"Mixtures of urea and ammonium nitrate in aqueous or ammoniac"},
    {c:"31029000",n:"矿物或化学氮肥（不包括尿素、硫酸铵、硝酸铵、硝酸钠、硝酸铵与硫酸铵或钙的复盐及混合物、尿素与硝酸铵的水溶液或氨溶液混合物",e:"Mineral or chemical nitrogen fertilisers (excl. urea; ammoni"},
    {c:"31051000",n:"动植物来源的矿物或化学肥料，呈片剂或类似形态或毛重≤10 千克包装",e:"Mineral or chemical fertilisers of animal or vegetable origi"},
    {c:"31052010",n:"含磷钾矿物或化学肥料，按干无水品重量计含氮量＞10%（不包括呈片剂或类似形态或毛重≤10 千克包装的产品）",e:"Mineral or chemical fertilisers containing phosphorus and po"},
    {c:"31052090",n:"含氮磷钾矿物或化学肥料，按干无水品重量计含氮量≤10%（不包括呈片剂或类似形态或毛重≤10 千克包装的产品）",e:"Mineral or chemical fertilisers containing nitrogen, phospho"},
    {c:"31053000",n:"磷酸氢二铵（磷酸二铵）（不包括呈片剂或类似形态或毛重≤10 千克包装的产品）",e:"Diammonium hydrogenorthophosphate \"diammonium phosphate\" (ex"},
    {c:"31054000",n:"磷酸二氢铵（磷酸一铵），无论是否与磷酸氢二铵（磷酸二铵）混合（不包括呈片剂或类似形态或毛重≤10 千克包装的产品）",e:"Ammonium dihydrogenorthophosphate \"monoammonium phosphate\", "},
    {c:"31055100",n:"含硝酸盐和磷酸盐的矿物或化学肥料（不包括磷酸二氢铵（磷酸一铵）、磷酸氢二铵（磷酸二铵），以及呈片剂或类似形态或毛重≤10",e:"Mineral or chemical fertilisers containing nitrates and phos"},
    {c:"31055900",n:"含氮（不含硝酸盐）和磷两种施肥元素但不含硝酸盐的矿物或化学肥料（不包括磷酸二氢铵（磷酸一铵）、磷酸氢二铵（磷酸二铵），以",e:"Mineral or chemical fertilisers containing the two fertilisi"},
    {c:"31059020",n:"含氮钾两种施肥元素或仅含一种主要施肥物质的矿物或化学肥料（包括动植物肥料与化学或矿物肥料的混合物），按重量计含氮量＞10",e:"Mineral or chemical fertilisers containing the two fertilisi"},
    {c:"31059080",n:"含氮钾两种施肥元素或仅含一种主要施肥元素的矿物或化学肥料（包括动植物肥料与化学或矿物肥料的混合物），不含氮或按重量计含氮",e:"Mineral or chemical fertilisers containing the two fertilisi"},
    {c:"72011011",n:"非合金生铁，呈块状或其他初级形态，按重量计含磷量≤0.5%、含锰量≥0.4%、含硅量≤1%",e:"Non-alloy pig iron in pigs, blocks or other primary forms, c"},
    {c:"72011019",n:"非合金生铁，呈块状或其他初级形态，按重量计含磷量≤0.5%、含锰量≥0.4%、含硅量＞1%",e:"Non-alloy pig iron in pigs, blocks or other primary forms, c"},
    {c:"72011030",n:"非合金生铁，呈块状或其他初级形态，按重量计含磷量≤0.5%、含锰量≥0.1% 但＜0.4%",e:"Non-alloy pig iron in pigs, blocks or other primary forms, c"},
    {c:"72011090",n:"非合金生铁，呈块状或其他初级形态，按重量计含磷量≤0.5%、含锰量≤0.1%",e:"Non-alloy pig iron in pigs, blocks or other primary forms, c"},
    {c:"72012000",n:"非合金生铁，呈块状或其他初级形态，按重量计含磷量≥0.5%",e:"Non-alloy pig iron in pigs, blocks or other primary forms, c"},
    {c:"72015010",n:"合金生铁，呈块状或其他初级形态，按重量计含钛量≥0.3% 但≤1%、含钒量≥0.5% 但≤1%",e:"Alloy pig iron in pigs, blocks or other primary forms, conta"},
    {c:"72015090",n:"合金生铁，呈块状或其他初级形态（不包括按重量计含钛量≥0.3% 但≤1% 且含钒量≥0.5% 但≤1% 的合金生铁）",e:"Alloy pig iron and spiegeleisen, in pigs, blocks or other pr"},
    {c:"72021120",n:"锰铁，按重量计含碳量＞2%，粒度≤5 毫米且按重量计含锰量＞65%",e:"Ferro-manganese, containing by weight > 2% carbon, with a gr"},
    {c:"72021180",n:"锰铁，按重量计含碳量＞2%（不包括粒度≤5 毫米且按重量计含锰量＞65% 的锰铁）",e:"Ferro-manganese, containing by weight > 2% carbon (excl. fer"},
    {c:"72021900",n:"锰铁，按重量计含碳量≤2%",e:"Ferro-manganese, containing by weight <= 2% carbon"},
    {c:"72024110",n:"铬铁，按重量计含碳量＞4% 但≤6%",e:"Ferro-chromium, containing by weight > 4% but <= 6% carbon"},
    {c:"72024190",n:"铬铁，按重量计含碳量＞6%",e:"Ferro-chromium, containing by weight > 6% carbon"},
    {c:"72024910",n:"铬铁，按重量计含碳量≤0.05%",e:"Ferro-chromium, containing by weight <= 0,05% carbon"},
    {c:"72024950",n:"铬铁，按重量计含碳量＞0.05% 但≤0.5%",e:"Ferro-chromium, containing by weight > 0,05% but <= 0,5% car"},
    {c:"72024990",n:"铬铁，按重量计含碳量＞0.5% 但≤4%",e:"Ferro-chromium, containing by weight > 0,5% but <= 4% carbon"},
    {c:"72026000",n:"镍铁",e:"Ferro-nickel"},
    {c:"72031000",n:"铁矿石直接还原制得的铁产品，呈块状、团状或类似形态",e:"Ferrous products obtained by direct reduction of iron ore, i"},
    {c:"72039000",n:"熔融生铁雾化制得的海绵铁产品，纯度≥99.94% 的铁，呈块状、团状或类似形态",e:"Spongy ferrous products, obtained from molten pig iron by at"},
    {c:"72051000",n:"生铁、镜铁、铁或钢的颗粒（不包括铁合金颗粒、铁或钢的车削及锉屑、某些小口径制品、滚珠轴承用残次滚珠）",e:"Granules, of pig iron, spiegeleisen, iron or steel (excl. gr"},
    {c:"72052100",n:"合金钢粉末（不包括铁合金粉末及放射性铁粉末〈同位素〉）",e:"Powders, of alloy steel (excl. powders of ferro-alloys and r"},
    {c:"72052900",n:"生铁、镜铁、铁或非合金钢粉末（不包括铁合金粉末及放射性铁粉末〈同位素〉）",e:"Powders, of pig iron, spiegeleisen, iron or non-alloy steel "},
    {c:"72061000",n:"铁及非合金钢锭（不包括废钢重熔锭、连铸产品、品目 7203 的铁）",e:"Ingots, of iron and non-alloy steel (excl. remelted scrap in"},
    {c:"72069000",n:"铁及非合金钢，呈搅炼条或其他初级形态（不包括钢锭、废钢重熔锭、连铸产品、品目 7203 的铁）",e:"Iron and non-alloy steel, in puddled bars or other primary f"},
    {c:"72071111",n:"非合金易切削钢半成品，按重量计含碳量＜0.25%，截面为方形或矩形、宽度小于厚度两倍，经轧制或连铸制得",e:"Semi-finished products, of non-alloy free-cutting steel, con"},
    {c:"72071114",n:"铁或非合金钢半成品，按重量计含碳量＜0.25%，截面为方形或矩形、宽度小于厚度两倍且厚度≤130 毫米，经轧制或连铸制得",e:"Semi-finished products, of iron or non-alloy steel, containi"},
    {c:"72071116",n:"铁或非合金钢半成品，按重量计含碳量＜0.25%，截面为方形或矩形、宽度小于厚度两倍且厚度＞130 毫米，经轧制或连铸制得",e:"Semi-finished products, of iron or non-alloy steel, containi"},
    {c:"72071190",n:"铁或非合金钢半成品，按重量计含碳量＜0.25%，截面为矩形、宽度小于厚度两倍，经锻造制得",e:"Semi-finished products of iron or non-alloy steel, containin"},
    {c:"72071210",n:"铁或非合金钢半成品，按重量计含碳量＜0.25%，截面为矩形（非方形）、宽度≥厚度两倍，经轧制或连铸制得",e:"Semi-finished products of iron or non-alloy steel, containin"},
    {c:"72071290",n:"铁或非合金钢半成品，按重量计含碳量＜0.25%，截面为矩形（非方形）、宽度≥厚度两倍，经锻造制得",e:"Semi-finished products of iron or non-alloy steel, containin"},
    {c:"72071912",n:"铁或非合金钢半成品，按重量计含碳量＜0.25%，截面为圆形或多边形，经轧制或连铸制得",e:"Semi-finished products, of iron or non-alloy steel, containi"},
    {c:"72071919",n:"铁或非合金钢半成品，按重量计含碳量＜0.25%，截面为圆形或多边形，经锻造制得",e:"Semi-finished products of iron or non-alloy steel, containin"},
    {c:"72071980",n:"铁或非合金钢半成品，按重量计含碳量＜0.25%（不包括截面为方形、矩形、圆形或多边形的半成品）",e:"Semi-finished products of iron or non-alloy steel, containin"},
    {c:"72072011",n:"非合金易切削钢半成品，按重量计含碳量≥0.25%，截面为方形或矩形、宽度小于厚度两倍，经轧制或连铸制得",e:"Semi-finished products, of non-alloy free-cutting steel, con"},
    {c:"72072015",n:"铁或非合金钢半成品，按重量计含碳量≥0.25% 但＜0.6%，截面为方形或矩形、宽度小于厚度两倍，经轧制或连铸制得（不包",e:"Semi-finished products of iron or non-alloy steel, containin"},
    {c:"72072017",n:"铁或非合金钢半成品，按重量计含碳量≥0.6%，截面为方形或矩形、宽度小于厚度两倍，经轧制或连铸制得（不包括易切削钢）",e:"Semi-finished products of iron or non-alloy steel, containin"},
    {c:"72072019",n:"铁或非合金钢半成品，按重量计含碳量≥0.25%，截面为方形或矩形、宽度小于厚度两倍，经锻造制得",e:"Semi-finished products of iron or non-alloy steel, containin"},
    {c:"72072032",n:"铁或非合金钢半成品，按重量计含碳量≥0.25%，截面为矩形（非方形）、宽度≥厚度两倍，经轧制或连铸制得",e:"Semi-finished products of iron or non-alloy steel, containin"},
    {c:"72072039",n:"铁或非合金钢半成品，按重量计含碳量≥0.25%，截面为矩形（非方形）且宽度≥厚度两倍，经锻造制得",e:"Semi-finished products of iron or non-alloy steel, containin"},
    {c:"72072052",n:"铁或非合金钢半成品，按重量计含碳量≥0.25%，截面为圆形或多边形，经轧制或连铸制得",e:"Semi-finished products of iron or non-alloy steel, containin"},
    {c:"72072059",n:"铁或非合金钢半成品，按重量计含碳量≥0.6%，截面为圆形或多边形，经锻造制得",e:"Semi-finished products of iron or non-alloy steel, containin"},
    {c:"72072080",n:"铁或非合金钢半成品，按重量计含碳量≥0.25%（不包括截面为方形、矩形、圆形或多边形的产品）",e:"Semi-finished products of iron or non-alloy steel, containin"},
    {c:"72081000",n:"铁或非合金钢平板轧材，宽度≥600 毫米，呈卷材状，仅经热轧、未包覆未镀未涂层，带有轧制工艺直接形成的凸纹图案",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72082500",n:"铁或非合金钢平板轧材，宽度≥600 毫米，呈卷材状，仅经热轧、未包覆未镀未涂层，厚度≥4.75 毫米，经酸洗，无凸纹图案",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72082600",n:"铁或非合金钢平板轧材，宽度≥600 毫米，呈卷材状，仅经热轧、未包覆未镀未涂层，厚度≥3 毫米但＜4.75 毫米，经酸洗",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72082700",n:"铁或非合金钢平板轧材，宽度≥600 毫米，呈卷材状，仅经热轧、未包覆未镀未涂层，厚度＜3 毫米，经酸洗，无凸纹图案",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72083600",n:"铁或非合金钢平板轧材，宽度≥600 毫米，呈卷材状，仅经热轧、未包覆未镀未涂层，厚度≥10 毫米，未经酸洗，无凸纹图案",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72083700",n:"铁或非合金钢平板轧材，宽度≥600 毫米，呈卷材状，仅经热轧、未包覆未镀未涂层，厚度≥4.75 毫米但＜10 毫米，未经",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72083800",n:"铁或非合金钢平板轧材，宽度≥600 毫米，呈卷材状，仅经热轧、未包覆未镀未涂层，厚度≥3 毫米但＜4.75 毫米，未经酸",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72083900",n:"铁或非合金钢平板轧材，宽度≥600 毫米，呈卷材状，仅经热轧、未包覆未镀未涂层，厚度＜3 毫米，未经酸洗，无凸纹图案",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72084000",n:"铁或非合金钢平板轧材，宽度≥600 毫米，非卷材状，仅经热轧、未包覆未镀未涂层，带有轧制工艺直接形成的凸纹图案",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72085120",n:"铁或非合金钢平板轧材，宽度≥600 毫米，非卷材状，仅经热轧、未包覆未镀未涂层，厚度＞15 毫米，无凸纹图案",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72085191",n:"铁或非合金钢平板轧材，宽度≥2050 毫米，非卷材状，仅经热轧、未包覆未镀未涂层，厚度＞10 毫米但≤15 毫米，无凸纹",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72085198",n:"铁或非合金钢平板轧材，宽度＜2050 毫米但≥600 毫米，非卷材状，仅经热轧、未包覆未镀未涂层，厚度＞10 毫米但≤1",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72085210",n:"铁或非合金钢平板轧材，宽度≤1250 毫米，非卷材状，经四面热轧或闭口箱形孔型热轧、未包覆未镀未涂层，厚度≥4.75 毫",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72085291",n:"铁或非合金钢平板轧材，宽度≥2050 毫米，非卷材状，仅经热轧、未包覆未镀未涂层，厚度≥4.75 毫米但≤10 毫米，无",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72085299",n:"铁或非合金钢平板轧材，宽度＜2050 毫米但≥600 毫米，非卷材状，仅经热轧、未包覆未镀未涂层，厚度≥4.75 毫米但",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72085310",n:"铁或非合金钢平板轧材，宽度≤1250 毫米，非卷材状，经四面热轧或闭口箱形孔型热轧、未包覆未镀未涂层，厚度≥4 毫米但＜",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72085390",n:"铁或非合金钢平板轧材，宽度≥600 毫米，非卷材状，仅经热轧、未包覆未镀未涂层，厚度≥3 毫米但＜4.75 毫米，无凸纹",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72085400",n:"铁或非合金钢平板轧材，宽度≥600 毫米，非卷材状，仅经热轧、未包覆未镀未涂层，厚度＜3 毫米，无凸纹图案",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72089020",n:"铁或钢平板轧材，宽度≥600 毫米，经热轧并进一步加工、未包覆未镀未涂层，带孔",e:"Flat-rolled products of iron or steel, of a width >= 600 mm,"},
    {c:"72089080",n:"铁或钢平板轧材，宽度≥600 毫米，经热轧并进一步加工、未包覆未镀未涂层，无孔",e:"Flat-rolled products of iron or steel, of a width >= 600 mm,"},
    {c:"72091500",n:"铁或非合金钢平板轧材，宽度≥600 毫米，呈卷材状，仅经冷轧（冷压延）、未包覆未镀未涂层，厚度≥3 毫米",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72091610",n:"铁或非合金钢平板轧材，宽度≥600 毫米，呈卷材状，仅经冷轧（冷压延），厚度＞1 毫米但＜3 毫米，电工用",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72091690",n:"铁或非合金钢平板轧材，宽度≥600 毫米，呈卷材状，仅经冷轧（冷压延）、未包覆未镀未涂层，厚度＞1 毫米但＜3 毫米（不",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72091710",n:"铁或非合金钢平板轧材，宽度≥600 毫米，呈卷材状，仅经冷轧（冷压延），厚度≥0.5 毫米但≤1 毫米，电工用",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72091790",n:"铁或非合金钢平板轧材，宽度≥600 毫米，呈卷材状，仅经冷轧（冷压延）、未包覆未镀未涂层，厚度≥0.5 毫米但≤1 毫米",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72091810",n:"铁或非合金钢平板轧材，宽度≥600 毫米，呈卷材状，仅经冷轧（冷压延），厚度＜0.5 毫米，电工用",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72091891",n:"铁或非合金钢平板轧材，宽度≥600 毫米，呈卷材状，仅经冷轧（冷压延）、未包覆未镀未涂层，厚度≥0.35 毫米但＜0.5",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72091899",n:"铁或非合金钢平板轧材，宽度≥600 毫米，呈卷材状，仅经冷轧（冷压延）、未包覆未镀未涂层，厚度＜0.35 毫米（不包括电",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72092500",n:"铁或非合金钢平板轧材，宽度≥600 毫米，非卷材状，仅经冷轧（冷压延）、未包覆未镀未涂层，厚度≥3 毫米",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72092610",n:"铁或非合金钢平板轧材，宽度≥600 毫米，非卷材状，仅经冷轧（冷压延），厚度＞1 毫米但＜3 毫米，电工用",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72092690",n:"铁或非合金钢平板轧材，宽度≥600 毫米，非卷材状，仅经冷轧（冷压延）、未包覆未镀未涂层，厚度＞1 毫米但＜3 毫米（不",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72092710",n:"铁或非合金钢平板轧材，宽度≥600 毫米，非卷材状，仅经冷轧（冷压延），厚度≥0.5 毫米但≤1 毫米，电工用",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72092790",n:"铁或非合金钢平板轧材，宽度≥600 毫米，非卷材状，仅经冷轧（冷压延）、未包覆未镀未涂层，厚度≥0.5 毫米但≤1 毫米",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72092810",n:"铁或非合金钢平板轧材，宽度≥600 毫米，非卷材状，仅经冷轧（冷压延），厚度＜0.5 毫米，电工用",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72092890",n:"铁或非合金钢平板轧材，宽度≥600 毫米，非卷材状，仅经冷轧（冷压延）、未包覆未镀未涂层，厚度＜0.5 毫米（不包括电工",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72099020",n:"铁或钢平板轧材，宽度≥600 毫米，经冷轧（冷压延）并进一步加工、未包覆未镀未涂层，带孔",e:"Flat-rolled products of iron or steel, of a width of >= 600 "},
    {c:"72099080",n:"铁或钢平板轧材，宽度≥600 毫米，经冷轧（冷压延）并进一步加工、未包覆未镀未涂层，无孔",e:"Flat-rolled products of iron or steel, of a width of >= 600 "},
    {c:"72101100",n:"铁或非合金钢平板轧材，宽度≥600 毫米，经热轧或冷轧（冷压延）、镀锡，厚度≥0.5 毫米",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72101220",n:"铁或非合金钢镀锡薄板，宽度≥600 毫米且厚度＜0.5 毫米，镀锡〔涂覆按重量计含锡≥97% 的金属层〕，仅经表面处理（",e:"Tinplate of iron or non-alloy steel, of a width of >= 600 mm"},
    {c:"72101280",n:"铁或非合金钢平板轧材，宽度≥600 毫米，经热轧或冷轧（冷压延）、镀锡，厚度＜0.5 毫米（不包括镀锡薄板）",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72102000",n:"铁或非合金钢平板轧材，宽度≥600 毫米，经热轧或冷轧（冷压延）、镀铅（包括铅锡合金镀板）",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72103000",n:"铁或非合金钢平板轧材，宽度≥600 毫米，经热轧或冷轧（冷压延）、电镀锌",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72104100",n:"铁或非合金钢平板轧材，宽度≥600 毫米，经热轧或冷轧（冷压延）、瓦楞状、镀锌（不包括电镀锌产品）",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72104900",n:"铁或非合金钢平板轧材，宽度≥600 毫米，经热轧或冷轧（冷压延）、非瓦楞状、镀锌（不包括电镀锌产品）",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72105000",n:"铁或非合金钢平板轧材，宽度≥600 毫米，经热轧或冷轧（冷压延）、镀氧化铬或铬与氧化铬混合物",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72106100",n:"铁或非合金钢平板轧材，宽度≥600 毫米，经热轧或冷轧（冷压延）、镀铝锌合金",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72106900",n:"铁或非合金钢平板轧材，宽度≥600 毫米，经热轧或冷轧（冷压延）、镀铝（不包括镀铝锌合金的产品）",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72107010",n:"镀锡薄板，宽度≥600 毫米且厚度＜0.5 毫米，镀锡〔涂覆按重量计含锡≥97% 的金属层〕，仅经涂漆（未进一步加工）；",e:"Tinplate of a width of >= 600 mm and of a thickness of < 0,5"},
    {c:"72107080",n:"铁或非合金钢平板轧材，宽度≥600 毫米，经热轧或冷轧（冷压延）、涂漆、涂清漆或覆塑料层（不包括经涂漆的镀锡薄板及电镀铬",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72109030",n:"铁或非合金钢平板轧材，宽度≥600 毫米，经热轧或冷轧（冷压延）、包覆",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72109040",n:"铁或非合金钢平板轧材，宽度≥600 毫米，经热轧或冷轧（冷压延）、镀锡并印刷",e:"Flat-rolled products of iron or non-alloy steel, tinned and "},
    {c:"72109080",n:"铁或非合金钢平板轧材，宽度≥600 毫米，经热轧或冷轧（冷压延）、镀或涂覆（不包括镀锡、镀铅（含铅锡合金镀板）、镀锌、镀",e:"Flat-rolled products of iron or non-alloy steel, hot-rolled "},
    {c:"72111300",n:"铁或非合金钢平板轧材，经四面热轧或闭口箱形孔型热轧、未包覆未镀未涂层，宽度＞150 毫米但＜600 毫米且厚度≥4 毫米",e:"Flat-rolled products of iron or non-alloy steel, simply hot-"},
    {c:"72111400",n:"铁或非合金钢平板轧材，宽度＜600 毫米，仅经热轧（未进一步加工）、未包覆未镀未涂层，厚度≥4.75 毫米（不包括宽扁钢",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72111900",n:"铁或非合金钢平板轧材，宽度＜600 毫米，仅经热轧、未包覆未镀未涂层，厚度＜4.75 毫米（不包括宽扁钢）",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72112320",n:"铁或非合金钢平板轧材，宽度＜600 毫米，仅经冷轧（冷压延）、未包覆未镀未涂层，按重量计含碳量＜0.25%，电工用",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72112330",n:"铁或非合金钢平板轧材，宽度＜600 毫米且厚度≥0.35 毫米，仅经冷轧（冷压延）、未包覆未镀未涂层，按重量计含碳量＜0",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72112380",n:"铁或非合金钢平板轧材，宽度＜600 毫米且厚度＜0.35 毫米，仅经冷轧（冷压延）、未包覆未镀未涂层，按重量计含碳量＜0",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72112900",n:"铁或非合金钢平板轧材，宽度＜600 毫米，仅经冷轧（冷压延）、未包覆未镀未涂层，按重量计含碳量≥0.25%",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72119020",n:"铁或非合金钢平板轧材，宽度＜600 毫米，经热轧或冷轧（冷压延）并进一步加工、未包覆未镀未涂层，带孔",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72119080",n:"铁或非合金钢平板轧材，宽度＜600 毫米，经热轧或冷轧（冷压延）并进一步加工、未包覆未镀未涂层，无孔",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72121010",n:"铁或非合金钢镀锡薄板，宽度＜600 毫米且厚度＜0.5 毫米，镀锡〔涂覆按重量计含锡≥97% 的金属层〕，仅经表面处理（",e:"Tinplate of iron or non-alloy steel, of a width of < 600 mm "},
    {c:"72121090",n:"铁或非合金钢平板轧材，宽度＜600 毫米，经热轧或冷轧（冷压延）、镀锡（不包括仅经表面处理的镀锡薄板）",e:"Flat-rolled products of iron or non-alloy steel, hot-rolled "},
    {c:"72122000",n:"铁或非合金钢平板轧材，宽度＜600 毫米，经热轧或冷轧（冷压延）、电镀锌",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72123000",n:"铁或非合金钢平板轧材，宽度＜600 毫米，经热轧或冷轧（冷压延）、镀锌（不包括电镀锌产品）",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72124020",n:"镀锡薄板，宽度＜600 毫米且厚度＜0.5 毫米，镀锡〔涂覆按重量计含锡≥97% 的金属层〕，仅经涂漆（未进一步加工）；",e:"Tinplate of a width of < 600 mm and of a thickness of < 0,5 "},
    {c:"72124080",n:"铁或非合金钢平板轧材，宽度＜600 毫米，经热轧或冷轧（冷压延）、涂漆、涂清漆或覆塑料层（不包括经涂漆的镀锡薄板及镀氧化",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72125020",n:"铁或非合金钢平板轧材，宽度＜600 毫米，经热轧或冷轧（冷压延）、镀氧化铬或铬与氧化铬混合物（不包括经涂漆的产品）",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72125030",n:"铁或非合金钢平板轧材，宽度＜600 毫米，经热轧或冷轧（冷压延）、镀铬或镀镍",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72125040",n:"铁或非合金钢平板轧材，宽度＜600 毫米，经热轧或冷轧（冷压延）、镀铜",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72125061",n:"铁或非合金钢平板轧材，宽度＜600 毫米，经热轧或冷轧（冷压延）、镀铝锌合金",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72125069",n:"铁或非合金钢平板轧材，宽度＜600 毫米，经热轧或冷轧（冷压延）、镀铝（不包括镀铝锌合金的产品）",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72125090",n:"铁或非合金钢平板轧材，宽度＜600 毫米，经热轧或冷轧（冷压延）、包覆（不包括镀锡、镀锌、镀铜、镀氧化铬或铬与氧化铬混合",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72126000",n:"铁或非合金钢平板轧材，宽度＜600 毫米，经热轧或冷轧（冷压延）、包覆",e:"Flat-rolled products of iron or non-alloy steel, of a width "},
    {c:"72131000",n:"铁或非合金钢热轧条杆，呈不规则盘卷状，带有轧制过程中产生的压痕、凸肋、凹槽或其他变形",e:"Bars and rods, hot-rolled, in irregularly wound coils of iro"},
    {c:"72132000",n:"非合金易切削钢热轧条杆，呈不规则盘卷状（不包括带有轧制过程中产生的压痕、凸肋、凹槽或其他变形的条杆）",e:"Bars and rods, hot-rolled, in irregularly wound coils, of no"},
    {c:"72139110",n:"铁或非合金钢热轧条杆，混凝土钢筋用、光面、呈不规则盘卷状，截面为圆形且直径＜14 毫米",e:"Bars and rods, hot-rolled, of the type used for concrete rei"},
    {c:"72139120",n:"铁或非合金钢热轧条杆，轮胎帘线用、光面、呈不规则盘卷状",e:"Bars and rods, hot-rolled, of the type used for tyre cord, s"},
    {c:"72139141",n:"铁或非合金钢热轧条杆，呈不规则盘卷状，按重量计含碳量≤0.06%，截面为圆形且直径＜14 毫米（不包括易切削钢产品、混凝",e:"Bars and rods, hot-rolled, of iron or non-alloy steel, in ir"},
    {c:"72139149",n:"铁或非合金钢热轧条杆，呈不规则盘卷状，按重量计含碳量＞0.06% 但＜0.25%，截面为圆形且直径＜14 毫米（不包括易",e:"Bars and rods, hot-rolled, of iron or non-alloy steel, in ir"},
    {c:"72139170",n:"铁或非合金钢热轧条杆，呈不规则盘卷状，按重量计含碳量≥0.25% 但≤0.75%，截面为圆形且直径＜14 毫米（不包括易",e:"Bars and rods, hot-rolled, in irregularly wound coils, of ir"},
    {c:"72139190",n:"铁或非合金钢热轧条杆，呈不规则盘卷状，按重量计含碳量＞0.75%，截面为圆形且直径＜14 毫米（不包括易切削钢产品、轮胎",e:"Bars and rods, hot-rolled, of iron or non-alloy steel, in ir"},
    {c:"72139910",n:"铁或非合金钢热轧条杆，呈不规则盘卷状，按重量计含碳量＜0.25%（不包括截面为圆形且直径＜14 毫米的产品、易切削钢条杆",e:"Bars and rods, of iron or non-alloy steel, hot-rolled, in ir"},
    {c:"72139990",n:"铁或非合金钢热轧条杆，呈不规则盘卷状，按重量计含碳量≥0.25%（不包括截面为圆形且直径＜14 毫米的产品、易切削钢条杆",e:"Bars and rods, hot-rolled, in irregularly wound coils, of ir"},
    {c:"72141000",n:"铁或非合金钢条杆，仅经锻造（未进一步加工）（不包括呈不规则盘卷状的产品）",e:"Bars and rods, of iron or non-alloy steel, not further worke"},
    {c:"72142000",n:"铁或非合金钢条杆，带有轧制过程中产生的压痕、凸肋、凹槽或其他变形",e:"Bars and rods, of iron or non-alloy steel, with indentations"},
    {c:"72143000",n:"非合金易切削钢条杆，仅经热轧、热拉拔或热挤压（未进一步加工）（不包括带有轧制过程中产生的压痕、凸肋、凹槽或其他变形的产品",e:"Bars and rods, of non-alloy free-cutting steel, not further "},
    {c:"72149110",n:"铁或非合金钢条杆，仅经热轧、热拉拔或热挤压（未进一步加工），按重量计含碳量＜0.25%，截面为矩形（非方形）（不包括带有",e:"Bars and rods of iron or non-alloy steel, not further worked"},
    {c:"72149190",n:"其他铁或非合金钢条杆，仅经热轧、热拉拔或热挤压，按重量计含碳量≥0.25%，截面为矩形（非方形）（不包括带有轧制过程中产",e:"Other bars and rods of iron or non-alloy steel, only hot-rol"},
    {c:"72149910",n:"铁或非合金钢条杆，混凝土钢筋用、光面，仅经热轧、热拉拔或热挤压，按重量计含碳量＜0.25%，截面为方形或非矩形",e:"Bars and rods of the type used for concrete reinforcement, s"},
    {c:"72149931",n:"铁或非合金钢条杆，仅经热轧、热拉拔或热挤压，按重量计含碳量＜0.25%，截面为圆形且最大直径≥80 毫米（不包括易切削钢",e:"Bars and rods of iron or non-alloy steel, only hot-rolled, h"},
    {c:"72149939",n:"铁或非合金钢条杆，仅经热轧、热拉拔或热挤压，按重量计含碳量＜0.25%，截面为圆形且最大直径＜80 毫米（不包括易切削钢",e:"Bars and rods of iron or non-alloy steel, only hot-rolled, h"},
    {c:"72149950",n:"铁或非合金钢条杆，仅经热轧、热拉拔或热挤压，按重量计含碳量＜0.25%，截面为方形或非方形、非圆形（不包括易切削钢产品、",e:"Bars and rods of iron or non-alloy steel, only hot-rolled, h"},
    {c:"72149971",n:"铁或非合金钢条杆，仅经热轧、热拉拔或热挤压，按重量计含碳量≥0.25%，截面为圆形且直径≥80 毫米（不包括带有轧制过程",e:"Bars and rods of iron or non-alloy steel, only hot-rolled, o"},
    {c:"72149979",n:"铁或非合金钢条杆，仅经热轧、热拉拔或热挤压，按重量计含碳量≥0.25%，截面为圆形且直径＜80 毫米（不包括带有轧制过程",e:"Bars and rods of iron or non-alloy steel, only hot-rolled, o"},
    {c:"72149995",n:"铁或非合金钢条杆，仅经热轧、热拉拔或热挤压，按重量计含碳量≥0.25%，截面为方形或非矩形、非圆形（不包括带有轧制过程中",e:"Bars and rods of iron or non-alloy steel, only hot-rolled, o"},
    {c:"72151000",n:"非合金易切削钢条杆，仅经冷加工成形或冷精整（未进一步加工）",e:"Bars and rods, of non-alloy free-cutting steel, not further "},
    {c:"72155011",n:"其他铁或非合金钢条杆，仅经冷加工成形或冷精整（未进一步加工），按重量计含碳量＜0.25%，截面为矩形（非方形）（不包括易",e:"Other bars and rods of iron or non-alloy steel, not further "},
    {c:"72155019",n:"其他铁或非合金钢条杆，仅经冷加工成形或冷精整（未进一步加工），按重量计含碳量＜0.25%，截面为方形或非矩形（不包括易切",e:"Other bars and rods of iron or non-alloy steel, not further "},
    {c:"72155080",n:"其他铁或非合金钢条杆，仅经冷加工成形或冷精整（未进一步加工），按重量计含碳量≥0.25%（不包括易切削钢产品）",e:"Other bars and rods of iron or non-alloy steel, not further "},
    {c:"72159000",n:"铁或非合金钢条杆，经冷加工成形或冷精整并进一步加工，或经热加工成形并进一步加工，其他未列名的",e:"Bars or rods, of iron or non-alloy steel, cold-formed or col"},
    {c:"72161000",n:"铁或非合金钢 U 形、I 形或 H 形型材，仅经热轧、热拉拔或挤压（未进一步加工），高度＜80 毫米",e:"U, I or H sections of iron or non-alloy steel, not further w"},
    {c:"72162100",n:"铁或非合金钢 L 形型材，仅经热轧、热拉拔或挤压（未进一步加工），高度＜80 毫米",e:"L sections of iron or non-alloy steel, not further worked th"},
    {c:"72162200",n:"铁或非合金钢 T 形型材，仅经热轧、热拉拔或挤压（未进一步加工），高度＜80 毫米",e:"T sections of iron or non-alloy steel, not further worked th"},
    {c:"72163110",n:"铁或非合金钢 U 形型材，仅经热轧、热拉拔或挤压，高度≥80 毫米但≤220 毫米",e:"U sections of iron or non-alloy steel, simply hot-rolled, ho"},
    {c:"72163190",n:"铁或非合金钢 U 形型材，仅经热轧、热拉拔或挤压，高度＞220 毫米",e:"U sections of iron or non-alloy steel, simply hot-rolled, ho"},
    {c:"72163211",n:"铁或非合金钢翼缘面平行的 I 形型材，仅经热轧、热拉拔或挤压，高度≥80 毫米但≤220 毫米",e:"I sections with parallel flange faces, of iron or non-alloy "},
    {c:"72163219",n:"铁或非合金钢 I 形型材，仅经热轧、热拉拔或挤压，高度≥80 毫米但≤220 毫米（不包括税号 7216.32.11 的",e:"I sections of iron or non-alloy steel, simply hot-rolled, ho"},
    {c:"72163291",n:"铁或非合金钢翼缘面平行的 I 形型材，仅经热轧、热拉拔或挤压，高度＞220 毫米",e:"I sections with parallel flange faces, of iron or non-alloy "},
    {c:"72163299",n:"铁或非合金钢 I 形型材，仅经热轧、热拉拔或挤压，高度＞220 毫米（不包括税号 7216.32.91 的产品）",e:"I sections of iron or non-alloy steel, simply hot-rolled, ho"},
    {c:"72163310",n:"铁或非合金钢 H 形型材，仅经热轧、热拉拔或挤压，高度≥80 毫米但≤180 毫米",e:"H sections of iron or non-alloy steel, simply hot-rolled, ho"},
    {c:"72163390",n:"铁或非合金钢 H 形型材，仅经热轧、热拉拔或挤压，高度＞180 毫米",e:"H sections of iron or non-alloy steel, simply hot-rolled, ho"},
    {c:"72164010",n:"铁或非合金钢 L 形型材，仅经热轧、热拉拔或挤压（未进一步加工），高度≥80 毫米",e:"L sections of iron or non-alloy steel, not further worked th"},
    {c:"72164090",n:"铁或非合金钢 T 形型材，仅经热轧、热拉拔或挤压（未进一步加工），高度≥80 毫米",e:"T sections of iron or non-alloy steel, not further worked th"},
    {c:"72165010",n:"铁或非合金钢型材，仅经热轧、热拉拔或热挤压（未进一步加工），截面可被边长≤80 毫米的正方形包围（不包括 U 形、I 形",e:"Sections of iron or non-alloy steel, not further worked than"},
    {c:"72165091",n:"球扁钢型材，仅经热轧、热拉拔或热挤压",e:"Bulb sections \"bulb flat\", only hot-rolled, hot-drawn or hot"},
    {c:"72165099",n:"铁或非合金钢异型材，仅经热轧、热拉拔或热挤压（不包括截面可被边长≤80 毫米的正方形包围的型材，以及 U 形、I 形、H",e:"Profile of iron or non-alloy steel, only hot-rolled, hot-dra"},
    {c:"72166110",n:"铁或非合金钢 C 形、L 形、U 形、Z 形、Ω 形或开口型材，由平板轧材经仅冷加工成形或冷精整制得",e:"c, l, u, z, omega or open-ended sections of iron or non-allo"},
    {c:"72166190",n:"铁或非合金钢角材、型材及异型材（非 C 形、L 形、U 形、Z 形、Ω 形或开口型材），由平板轧材经仅冷加工成形或冷精整",e:"Angles, shapes and sections (other than c, l, u, z, omega or"},
    {c:"72166900",n:"铁或非合金钢角材、型材及异型材，仅经冷加工成形或冷精整（未进一步加工）（不包括压型板）",e:"Angles, shapes and sections, of iron or non-alloy steel, not"},
    {c:"72169110",n:"铁或非合金钢压型板（肋形），经冷加工成形或冷精整",e:"Sheets sheets of iron or non-alloy steel, cold-formed or col"},
    {c:"72169180",n:"铁或非合金钢角材、型材及异型材，由平板轧材经冷加工成形或冷精整并进一步加工（不包括压型板）",e:"Angles, shapes and sections, of iron or non-alloy steel, col"},
    {c:"72169900",n:"铁或非合金钢角材、型材及异型材，经冷加工成形或冷精整并进一步加工，或经热锻、其他热加工成形并进一步加工，其他未列名的（不",e:"Angles, shapes and sections, of iron or non-alloy steel, col"},
    {c:"72171010",n:"铁或非合金钢线材，呈盘卷状，按重量计含碳量＜0.25%，未镀未涂层，无论是否抛光，最大截面尺寸＜0.8 毫米",e:"Wire of iron or non-alloy steel, in coils, containing by wei"},
    {c:"72171031",n:"铁或非合金钢线材，呈盘卷状，按重量计含碳量＜0.25%，带有轧制过程中产生的压痕、凸肋、凹槽或其他变形，未镀未涂层，最大",e:"Wire of iron or non-alloy steel, in coils, containing by wei"},
    {c:"72171039",n:"铁或非合金钢线材，呈盘卷状，按重量计含碳量＜0.25%，未镀未涂层，最大截面尺寸≥0.8 毫米（无轧制过程中产生的压痕、",e:"Wire of iron or non-alloy steel, in coils, containing by wei"},
    {c:"72171050",n:"铁或非合金钢线材，呈盘卷状，按重量计含碳量≥0.25% 但＜0.6%，未镀未涂层，无论是否抛光（不包括热轧条杆）",e:"Wire of iron or non-alloy steel, in coils, containing by wei"},
    {c:"72171090",n:"铁或非合金钢线材，呈盘卷状，按重量计含碳量≥0.6%，未镀未涂层，无论是否抛光（不包括热轧条杆）",e:"Wire of iron or non-alloy steel, in coils, containing by wei"},
    {c:"72172010",n:"铁或非合金钢线材，呈盘卷状，按重量计含碳量＜0.25%，镀锌，最大截面尺寸＜0.8 毫米",e:"Wire of iron or non-alloy steel, in coils, containing by wei"},
    {c:"72172030",n:"铁或非合金钢线材，呈盘卷状，按重量计含碳量＜0.25%，镀锌，最大截面尺寸＜0.8 毫米（不包括条杆）",e:"Wire of iron or non-alloy steel, in coils, containing by wei"},
    {c:"72172050",n:"铁或非合金钢线材，呈盘卷状，按重量计含碳量≥0.25% 但＜0.6%，镀锌（不包括条杆）",e:"Wire of iron or non-alloy steel, in coils, containing by wei"},
    {c:"72172090",n:"铁或非合金钢线材，呈盘卷状，按重量计含碳量≥0.6%，镀锌（不包括条杆）",e:"Wire of iron or non-alloy steel, in coils, containing by wei"},
    {c:"72173041",n:"铁或非合金钢线材，呈盘卷状，按重量计含碳量＜0.25%，镀铜（不包括条杆）",e:"Wire of iron or non-alloy steel, in coils, containing by wei"},
    {c:"72173049",n:"铁或非合金钢线材，呈盘卷状，按重量计含碳量＜0.25%，镀贱金属（不包括镀锌、镀铜产品及条杆）",e:"Wire of iron or non-alloy steel, in coils, containing by wei"},
    {c:"72173050",n:"铁或非合金钢线材，呈盘卷状，按重量计含碳量≥0.25% 但＜0.6%，镀贱金属（不包括镀锌产品及条杆）",e:"Wire of iron or non-alloy steel, in coils, containing by wei"},
    {c:"72173090",n:"铁或非合金钢线材，呈盘卷状，按重量计含碳量≥0.6%，镀贱金属（不包括镀锌产品及条杆）",e:"Wire of iron or non-alloy steel, in coils, containing by wei"},
    {c:"72179020",n:"铁或非合金钢线材，呈盘卷状，按重量计含碳量＜0.25%，经镀或涂覆（不包括镀或涂覆贱金属的产品及条杆）",e:"Wire of iron or non-alloy steel, in coils, containing by wei"},
    {c:"72179050",n:"铁或非合金钢线材，呈盘卷状，按重量计含碳量≥0.25% 但＜0.6%，经镀或涂覆（不包括镀或涂覆贱金属的产品及条杆）",e:"Wire of iron or non-alloy steel, in coils, containing by wei"},
    {c:"72179090",n:"铁或非合金钢线材，呈盘卷状，按重量计含碳量≥0.6%，经镀或涂覆（不包括镀或涂覆贱金属的产品及条杆）",e:"Wire of iron or non-alloy steel, in coils, containing by wei"},
    {c:"72181000",n:"不锈钢，呈锭状及其他初级形态（不包括锭状废碎料及连铸产品）",e:"Steel, stainless, in ingots and other primary forms (excl. w"},
    {c:"72189110",n:"不锈钢半成品，截面为矩形（非方形），按重量计含镍量≥2.5%",e:"Semi-finished products of stainless steel, of rectangular \"o"},
    {c:"72189180",n:"不锈钢半成品，截面为矩形（非方形），按重量计含镍量＜2.5%",e:"Semi-finished products of stainless steel, of rectangular \"o"},
    {c:"72189911",n:"不锈钢半成品，截面为方形，经轧制或连铸制得",e:"Semi-finished products of stainless steel, of square cross-s"},
    {c:"72189919",n:"不锈钢半成品，截面为方形，经锻造制得",e:"Semi-finished products of stainless steel, of square cross-s"},
    {c:"72189920",n:"不锈钢半成品，截面为圆形或非方非矩形，经轧制或连铸制得",e:"Semi-finished products of stainless steel, of circular cross"},
    {c:"72189980",n:"不锈钢半成品，经锻造制得（不包括截面为方形或矩形的产品）",e:"Semi-finished products of stainless steel, forged (excl. pro"},
    {c:"72191100",n:"不锈钢平板轧材，宽度≥600 毫米，仅经热轧（未进一步加工），呈卷材状，厚度＞10 毫米",e:"Flat-rolled products of stainless steel, of a width of >= 60"},
    {c:"72191210",n:"不锈钢平板轧材，宽度≥600 毫米，仅经热轧（未进一步加工），呈卷材状，厚度≥4.75 毫米但≤10 毫米，按重量计含镍",e:"Flat-rolled products of stainless steel, of a width of >= 60"},
    {c:"72191290",n:"不锈钢平板轧材，宽度≥600 毫米，仅经热轧（未进一步加工），呈卷材状，厚度≥4.75 毫米但≤10 毫米，按重量计含镍",e:"Flat-rolled products of stainless steel, of a width of >= 60"},
    {c:"72191310",n:"不锈钢平板轧材，宽度≥600 毫米，仅经热轧（未进一步加工），呈卷材状，厚度≥3 毫米但≤4.75 毫米，按重量计含镍量",e:"Flat-rolled products of stainless steel, of a width of >= 60"},
    {c:"72191390",n:"不锈钢平板轧材，宽度≥600 毫米，仅经热轧（未进一步加工），呈卷材状，厚度≥3 毫米但≤4.75 毫米，按重量计含镍量",e:"Flat-rolled products of stainless steel, of a width of >= 60"},
    {c:"72191410",n:"不锈钢平板轧材，宽度≥600 毫米，仅经热轧（未进一步加工），呈卷材状，厚度＜3 毫米，按重量计含镍量≥2.5%",e:"Flat-rolled products of stainless steel, of a width of >= 60"},
    {c:"72191490",n:"不锈钢平板轧材，宽度≥600 毫米，仅经热轧（未进一步加工），呈卷材状，厚度＜3 毫米，按重量计含镍量＜2.5%",e:"Flat-rolled products of stainless steel, of a width of >= 60"},
    {c:"72192110",n:"不锈钢平板轧材，宽度≥600 毫米，仅经热轧（未进一步加工），非卷材状，厚度＞10 毫米，按重量计含镍量≥2.5%",e:"Flat-rolled products of stainless steel, of a width of >= 60"},
    {c:"72192190",n:"不锈钢平板轧材，宽度≥600 毫米，仅经热轧（未进一步加工），非卷材状，厚度＞10 毫米，按重量计含镍量＜2.5%",e:"Flat-rolled products of stainless steel, of a width of >= 60"},
    {c:"72192210",n:"不锈钢平板轧材，宽度≥600 毫米，仅经热轧（未进一步加工），非卷材状，厚度≥4.75 毫米但≤10 毫米，按重量计含镍",e:"Flat-rolled products of stainless steel, of a width of >= 60"},
    {c:"72192290",n:"不锈钢平板轧材，宽度≥600 毫米，仅经热轧（未进一步加工），非卷材状，厚度≥4.75 毫米但≤10 毫米，按重量计含镍",e:"Flat-rolled products of stainless steel, of a width of >= 60"},
    {c:"72192300",n:"不锈钢平板轧材，宽度≥600 毫米，仅经热轧（未进一步加工），非卷材状，厚度≥3 毫米但＜4.75 毫米",e:"Flat-rolled products of stainless steel, of a width of >= 60"},
    {c:"72192400",n:"不锈钢平板轧材，宽度≥600 毫米，仅经热轧（未进一步加工），非卷材状，厚度＜3 毫米",e:"Flat-rolled products of stainless steel, of a width of >= 60"},
    {c:"72193100",n:"不锈钢平板轧材，宽度≥600 毫米，仅经冷轧（冷压延）（未进一步加工），厚度≥4.75 毫米",e:"Flat-rolled products of stainless steel, of a width of >= 60"},
    {c:"72193210",n:"不锈钢平板轧材，宽度≥600 毫米，仅经冷轧（冷压延）（未进一步加工），厚度≥3 毫米但≤4.75 毫米，按重量计含镍量",e:"Flat-rolled products of stainless steel, of a width of >= 60"},
    {c:"72193290",n:"不锈钢平板轧材，宽度≥600 毫米，仅经冷轧（冷压延）（未进一步加工），厚度≥3 毫米但≤4.75 毫米，按重量计含镍量",e:"Flat-rolled products of stainless steel, of a width of >= 60"},
    {c:"72193310",n:"不锈钢平板轧材，宽度≥600 毫米，仅经冷轧（冷压延）（未进一步加工），厚度＞1 毫米但＜3 毫米，按重量计含镍量≥2.",e:"Flat-rolled products of stainless steel, of a width of >= 60"},
    {c:"72193390",n:"不锈钢平板轧材，宽度≥600 毫米，仅经冷轧（冷压延）（未进一步加工），厚度＞1 毫米但＜3 毫米，按重量计含镍量＜2.",e:"Flat-rolled products of stainless steel, of a width of >= 60"},
    {c:"72193410",n:"不锈钢平板轧材，宽度≥600 毫米，仅经冷轧（冷压延）（未进一步加工），厚度≥0.5 毫米但≤1 毫米，按重量计含镍量≥",e:"Flat-rolled products of stainless steel, of a width of >= 60"},
    {c:"72193490",n:"不锈钢平板轧材，宽度≥600 毫米，仅经冷轧（冷压延）（未进一步加工），厚度≥0.5 毫米但≤1 毫米，按重量计含镍量＜",e:"Flat-rolled products of stainless steel, of a width of >= 60"},
    {c:"72193510",n:"不锈钢平板轧材，宽度≥600 毫米，仅经冷轧（冷压延）（未进一步加工），厚度＜0.5 毫米，按重量计含镍量≥2.5%",e:"Flat-rolled products of stainless steel, of a width of >= 60"},
    {c:"72193590",n:"不锈钢平板轧材，宽度≥600 毫米，仅经冷轧（冷压延）（未进一步加工），厚度＜0.5 毫米，按重量计含镍量＜2.5%",e:"Flat-rolled products of stainless steel, of a width of >= 60"},
    {c:"72199020",n:"不锈钢平板轧材，宽度≥600 毫米，经热轧或冷轧（冷压延）并进一步加工，带孔",e:"Flat-rolled products of stainless steel, of a width of >= 60"},
    {c:"72199080",n:"不锈钢平板轧材，宽度≥600 毫米，经热轧或冷轧（冷压延）并进一步加工，无孔",e:"Flat-rolled products of stainless steel, of a width of >= 60"},
    {c:"72201100",n:"不锈钢平板轧材，宽度＜600 毫米，仅经热轧（未进一步加工），厚度≥4.75 毫米",e:"Flat-rolled products of stainless steel, of a width of < 600"},
    {c:"72201200",n:"不锈钢平板轧材，宽度＜600 毫米，仅经热轧（未进一步加工），厚度＜4.75 毫米",e:"Flat-rolled products of stainless steel, of a width of < 600"},
    {c:"72202021",n:"不锈钢平板轧材，宽度＜600 毫米，仅经冷轧（冷压延）（未进一步加工），厚度≥3 毫米且按重量计含镍量≥2.5%",e:"Flat-rolled products of stainless steel, of a width of < 600"},
    {c:"72202029",n:"不锈钢平板轧材，宽度＜600 毫米，仅经冷轧（冷压延）（未进一步加工），厚度≥3 毫米且按重量计含镍量＜2.5%",e:"Flat-rolled products of stainless steel, of a width of < 600"},
    {c:"72202041",n:"不锈钢平板轧材，宽度＜600 毫米，仅经冷轧（冷压延）（未进一步加工），厚度＞0.35 毫米但＜3 毫米且按重量计含镍量",e:"Flat-rolled products of stainless steel, of a width of < 600"},
    {c:"72202049",n:"不锈钢平板轧材，宽度＜600 毫米，仅经冷轧（冷压延）（未进一步加工），厚度＞0.35 毫米但＜3 毫米且按重量计含镍量",e:"Flat-rolled products of stainless steel, of a width of < 600"},
    {c:"72202081",n:"不锈钢平板轧材，宽度＜600 毫米，仅经冷轧（冷压延）（未进一步加工），厚度≤0.35 毫米且按重量计含镍量≥2.5%",e:"Flat-rolled products of stainless steel, of a width of < 600"},
    {c:"72202089",n:"不锈钢平板轧材，宽度＜600 毫米，仅经冷轧（冷压延）（未进一步加工），厚度≤0.35 毫米且按重量计含镍量＜2.5%",e:"Flat-rolled products of stainless steel, of a width of < 600"},
    {c:"72209020",n:"不锈钢平板轧材，宽度＜600 毫米，经热轧或冷轧（冷压延）并进一步加工，带孔",e:"Flat-rolled products of stainless steel, of a width of < 600"},
    {c:"72209080",n:"不锈钢平板轧材，宽度＜600 毫米，经热轧或冷轧（冷压延）并进一步加工，无孔",e:"Flat-rolled products of stainless steel, of a width of < 600"},
    {c:"72210010",n:"不锈钢热轧条杆，呈不规则盘卷状，按重量计含镍量≥2.5%",e:"Bars and rods of stainless steel, hot-rolled, in irregularly"},
    {c:"72210090",n:"不锈钢热轧条杆，呈不规则盘卷状，按重量计含镍量＜2.5%",e:"Bars and rods of stainless steel, hot-rolled, in irregularly"},
    {c:"72221111",n:"不锈钢条杆，仅经热轧、热拉拔或挤压（未进一步加工），截面为圆形且直径≥800 毫米，按重量计含镍量≥2.5%",e:"Bars and rods of stainless steel, not further worked than ho"},
    {c:"72221119",n:"不锈钢条杆，仅经热轧、热拉拔或挤压（未进一步加工），截面为圆形且直径≥800 毫米，按重量计含镍量＜2.5%",e:"Bars and rods of stainless steel, not further worked than ho"},
    {c:"72221181",n:"不锈钢条杆，仅经热轧、热拉拔或挤压（未进一步加工），截面为圆形且直径＜80 毫米，按重量计含镍量≥2.5%",e:"Bars and rods of stainless steel, not further worked than ho"},
    {c:"72221189",n:"不锈钢条杆，仅经热轧、热拉拔或挤压（未进一步加工），截面为圆形且直径＜80 毫米，按重量计含镍量＜2.5%",e:"Bars and rods of stainless steel, not further worked than ho"},
    {c:"72221910",n:"不锈钢条杆，仅经热轧、热拉拔或挤压（未进一步加工），按重量计含镍量≥2.5%（不包括圆形截面的产品）",e:"Bars and rods of stainless steel, not further worked than ho"},
    {c:"72221990",n:"不锈钢条杆，仅经热轧、热拉拔或挤压（未进一步加工），按重量计含镍量＜2.5%（不包括圆形截面的产品）",e:"Bars and rods of stainless steel, not further worked than ho"},
    {c:"72222011",n:"不锈钢条杆，截面为圆形且直径≥80 毫米，仅经冷加工成形或冷精整，按重量计含镍量≥2.5%",e:"Bars and rods of stainless steel, of circular cross-section "},
    {c:"72222019",n:"不锈钢条杆，截面为圆形且直径≥80 毫米，仅经冷加工成形或冷精整，按重量计含镍量＜2.5%",e:"Bars and rods of stainless steel, of circular cross-section "},
    {c:"72222021",n:"不锈钢条杆，仅经冷加工成形或冷精整（未进一步加工），截面为圆形且直径≥25 毫米但＜80 毫米，按重量计含镍量≥2.5%",e:"Bars and rods of stainless steel, not further worked than co"},
    {c:"72222029",n:"不锈钢条杆，仅经冷加工成形或冷精整（未进一步加工），截面为圆形且直径≥25 毫米但＜80 毫米，按重量计含镍量＜2.5%",e:"Bars and rods of stainless steel, not further worked than co"},
    {c:"72222031",n:"不锈钢条杆，仅经冷加工成形或冷精整（未进一步加工），截面为圆形且直径＜25 毫米，按重量计含镍量≥2.5%",e:"Bars and rods of stainless steel, not further worked than co"},
    {c:"72222039",n:"不锈钢条杆，仅经冷加工成形或冷精整（未进一步加工），截面为圆形且直径＜25 毫米，按重量计含镍量＜2.5%",e:"Bars and rods of stainless steel, not further worked than co"},
    {c:"72222081",n:"不锈钢条杆，仅经冷加工成形或冷精整（未进一步加工），按重量计含镍量≥2.5%（不包括圆形截面的产品）",e:"Bars and rods of stainless steel, not further worked than co"},
    {c:"72222089",n:"不锈钢条杆，仅经冷加工成形或冷精整（未进一步加工），按重量计含镍量＜2.5%（不包括圆形截面的产品）",e:"Bars and rods of stainless steel, not further worked than co"},
    {c:"72223051",n:"其他不锈钢条杆，按重量计含镍量≥2.5%，经锻造制得",e:"Other bars and rods of stainless steel, containing by weight"},
    {c:"72223091",n:"其他不锈钢条杆，按重量计含镍量＜2.5%，经锻造制得",e:"Other bars and rods of stainless steel, containing by weight"},
    {c:"72223097",n:"不锈钢条杆，经冷加工成形或冷精整并进一步加工，或经热加工成形并进一步加工，其他未列名的（不包括锻造产品）",e:"Bars and rods of stainless steel, cold-formed or cold-finish"},
    {c:"72224010",n:"不锈钢角材、型材及异型材，仅经热轧、热拉拔或挤压",e:"Angles, shapes and sections of stainless steel, only hot-rol"},
    {c:"72224050",n:"不锈钢角材、型材及异型材，仅经冷加工成形或冷精整（未进一步加工）",e:"Angles, shapes and sections of stainless steel, not further "},
    {c:"72224090",n:"不锈钢角材、型材及异型材，经冷加工成形或冷精整并进一步加工，或仅经锻造（未进一步加工）、经锻造制得，或经其他热加工成形并",e:"Angles, shapes and sections of stainless steel, cold-formed "},
    {c:"72230011",n:"不锈钢线材，呈盘卷状，按重量计含镍量 28% 至 31% 且含铬量 20% 至 22%（不包括条杆）",e:"Wire of stainless steel, in coils, containing by weight 28% "},
    {c:"72230019",n:"不锈钢线材，呈盘卷状，按重量计含镍量≥2.5%（不包括含镍量 28% 至 31% 且含铬量 20% 至 22% 的产品及",e:"Wire of stainless steel, in coils, containing by weight >= 2"},
    {c:"72230091",n:"不锈钢线材，呈盘卷状，按重量计含镍量＜2.5%、含铬量 13% 至 25% 且含铝量 3.5% 至 6%（不包括条杆）",e:"Wire of stainless steel, in coils, containing by weight < 2,"},
    {c:"72230099",n:"不锈钢线材，呈盘卷状，按重量计含镍量＜2.5%（不包括含铬量 13% 至 25% 且含铝量 3.5% 至 6% 的产品及",e:"Wire of stainless steel, in coils, containing by weight < 2,"},
    {c:"72241010",n:"工具钢，呈锭状及其他初级形态",e:"Ingots and other primary forms, of tool steel"},
    {c:"72241090",n:"合金钢（非不锈钢），呈锭状及其他初级形态（不包括工具钢、锭状废碎料及连铸产品）",e:"Steel, alloy, other than stainless, in ingots or other prima"},
    {c:"72249002",n:"工具钢半成品",e:"Semi-finished products of tool steel"},
    {c:"72249003",n:"高速钢半成品，截面为方形或矩形，经热轧或连铸制得，宽度小于厚度的两倍",e:"Semi-finished products of high-speed steel, of square or rec"},
    {c:"72249005",n:"钢材半成品，按重量计含碳量≤0.7%、含锰量 0.5% 至 1.2%、含硅量 0.6% 至 2.3%；或按重量计含硼量≥",e:"Semi-finished products of steel containing by weight <= 0,7%"},
    {c:"72249007",n:"合金钢半成品（非不锈钢），截面为方形或矩形，经热轧或连铸制得，宽度小于厚度的两倍（不包括工具钢、高速钢及税号 7224.",e:"Semi-finished products of alloy steel other than stainless s"},
    {c:"72249014",n:"合金钢半成品（非不锈钢），截面为方形或矩形，经热轧或连铸制得，宽度大于等于厚度的两倍（不包括工具钢）",e:"Semi-finished products of alloy steel other than stainless s"},
    {c:"72249018",n:"合金钢半成品（非不锈钢），截面为方形或矩形，经锻造制得（不包括工具钢）",e:"Semi-finished products of alloy steel other than stainless s"},
    {c:"72249031",n:"钢材半成品，按重量计含碳量 0.9% 至 1.15%、含铬量 0.5% 至 2%，若含钼则钼含量≤0.5%，经热轧或连铸",e:"Semi-finished products of steel containing by weight 0,9% to"},
    {c:"72249038",n:"合金钢半成品（非不锈钢），经热轧或连铸制得并切割成非方形、非矩形的形状（不包括工具钢及含碳量 0.9% 至 1.15%、",e:"Semi-finished products of alloy steel, other than stainless "},
    {c:"72249090",n:"合金钢半成品（非不锈钢），经锻造制得（不包括工具钢及截面为方形、矩形、圆形或多边形的产品）",e:"Semi-finished products of alloy steel, other than stainless "},
    {c:"72251100",n:"硅电工钢平板轧材，宽度≥600 毫米，晶粒取向型",e:"Flat-rolled products of silicon-electrical steel, of a width"},
    {c:"72251910",n:"硅电工钢平板轧材，宽度≥600 毫米，经热轧制得",e:"Flat-rolled products of silicon-electrical steel, of a width"},
    {c:"72251990",n:"硅电工钢平板轧材，宽度≥600 毫米，经冷轧（冷压延）制得，非晶粒取向型",e:"Flat-rolled products of silicon-electrical steel, of a width"},
    {c:"72253010",n:"工具钢平板轧材，宽度≥600 毫米，仅经热轧（未进一步加工），呈卷材状",e:"Flat-rolled products of tool steel, of a width of >= 600 mm,"},
    {c:"72253030",n:"高速钢平板轧材，宽度≥600 毫米，仅经热轧（未进一步加工），呈卷材状",e:"Flat-rolled products of high-speed steel, of a width of >= 6"},
    {c:"72253090",n:"合金钢平板轧材（非不锈钢），宽度≥600 毫米，仅经热轧（未进一步加工），呈卷材状（不包括工具钢、高速钢或硅电工钢产品）",e:"Flat-rolled products of alloy steel other than stainless, of"},
    {c:"72254012",n:"工具钢平板轧材，宽度≥600 毫米，仅经热轧（未进一步加工），非卷材状",e:"Flat-rolled products of tool steel, of a width of >= 600 mm,"},
    {c:"72254015",n:"高速钢平板轧材，宽度≥600 毫米，仅经热轧（未进一步加工），非卷材状",e:"Flat-rolled products of high-speed steel, of a width of >= 6"},
    {c:"72254040",n:"合金钢平板轧材（非不锈钢），宽度≥600 毫米，仅经热轧（未进一步加工），非卷材状，厚度＞10 毫米（不包括工具钢、高速",e:"Flat-rolled products of alloy steel other than stainless, of"},
    {c:"72254060",n:"合金钢平板轧材（非不锈钢），宽度≥600 毫米，仅经热轧（未进一步加工），非卷材状，厚度≥4.75 毫米但≤10 毫米（",e:"Flat-rolled products of alloy steel other than stainless, of"},
    {c:"72254090",n:"合金钢平板轧材（非不锈钢），宽度≥600 毫米，仅经热轧（未进一步加工），非卷材状，厚度＜4.75 毫米（不包括工具钢、",e:"Flat-rolled products of alloy steel other than stainless, of"},
    {c:"72255020",n:"高速钢平板轧材，宽度≥600 毫米，仅经冷轧（冷压延）（未进一步加工）",e:"Flat-rolled products of high-speed steel, of a width of >= 6"},
    {c:"72255080",n:"合金钢平板轧材（非不锈钢），宽度≥600 毫米，仅经冷轧（冷压延）（未进一步加工）（不包括高速钢或硅电工钢产品）",e:"Flat-rolled products of alloy steel other than stainless, of"},
    {c:"72259100",n:"合金钢平板轧材（非不锈钢），宽度≥600 毫米，经热轧或冷轧（冷压延）并电镀锌（不包括硅电工钢产品）",e:"Flat-rolled products of alloy steel other than stainless, of"},
    {c:"72259200",n:"合金钢平板轧材（非不锈钢），宽度≥600 毫米，经热轧或冷轧（冷压延）并镀锌（不包括电镀锌产品及硅电工钢产品）",e:"Flat-rolled products of alloy steel other than stainless, of"},
    {c:"72259900",n:"合金钢平板轧材（非不锈钢），宽度≥600 毫米，经热轧或冷轧（冷压延）并进一步加工（不包括镀锌产品及硅电工钢产品）",e:"Flat-rolled products of alloy steel other than stainless, of"},
    {c:"72261100",n:"硅电工钢平板轧材，宽度＜600 毫米，经热轧或冷轧（冷压延）制得，晶粒取向型",e:"Flat-rolled products of silicon-electrical steel, of a width"},
    {c:"72261910",n:"硅电工钢平板轧材，宽度＜600 毫米，仅经热轧（未进一步加工）",e:"Flat-rolled products of silicon-electrical steel, of a width"},
    {c:"72261980",n:"硅电工钢平板轧材，宽度＜600 毫米，经冷轧（冷压延）制得（无论是否进一步加工），或经热轧并进一步加工制得，非晶粒取向型",e:"Flat-rolled products of silicon-electrical steel, of a width"},
    {c:"72262000",n:"高速钢平板轧材，宽度≤600 毫米，经热轧或冷轧（冷压延）制得",e:"Flat-rolled products of high-speed steel, of a width of <= 6"},
    {c:"72269120",n:"工具钢平板轧材，宽度＜600 毫米，仅经热轧制得",e:"Flat-rolled products of tool steel, of a width of < 600 mm, "},
    {c:"72269191",n:"合金钢平板轧材（非不锈钢），仅经热轧制得，厚度≥4.75 毫米，宽度＜600 毫米（不包括工具钢、硅电工钢或高速钢产品）",e:"Flat-rolled products of alloy steel other than stainless ste"},
    {c:"72269199",n:"合金钢平板轧材（非不锈钢），仅经热轧制得，厚度＜4.75 毫米，宽度＜600 毫米（不包括工具钢、硅电工钢或高速钢产品）",e:"Flat-rolled products of alloy steel other than stainless ste"},
    {c:"72269200",n:"合金钢平板轧材（非不锈钢），宽度＜600 毫米，仅经冷轧（冷压延）（未进一步加工）（不包括高速钢或硅电工钢产品）",e:"Flat-rolled products of alloy steel other than stainless, of"},
    {c:"72269910",n:"合金钢平板轧材（非不锈钢），宽度＜600 毫米，经热轧或冷轧（冷压延）并电镀锌（不包括高速钢或硅电工钢产品）",e:"Flat-rolled products of alloy steel other than stainless, of"},
    {c:"72269930",n:"合金钢平板轧材（非不锈钢），宽度＜600 毫米，经热轧或冷轧（冷压延）并镀锌（不包括电镀锌产品及高速钢、硅电工钢产品）",e:"Flat-rolled products of alloy steel other than stainless, of"},
    {c:"72269970",n:"合金钢平板轧材（非不锈钢），宽度＜600 毫米，经热轧或冷轧（冷压延）并进一步加工（不包括镀锌产品及高速钢、硅电工钢产品",e:"Flat-rolled products of alloy steel other than stainless, of"},
    {c:"72271000",n:"高速钢热轧条杆，呈不规则盘卷状",e:"Bars and rods of high-speed steel, hot-rolled, in irregularl"},
    {c:"72272000",n:"硅锰钢热轧条杆，呈不规则盘卷状",e:"Bars and rods of silico-manganese steel, hot-rolled, in irre"},
    {c:"72279010",n:"钢材热轧条杆，按重量计含硼量≥0.0008%，且其他元素含量均低于本章注释一 f 款所列最低含量，呈不规则盘卷状",e:"Bars and rods, hot-rolled, of steel containing by weight >= "},
    {c:"72279050",n:"钢材热轧条杆，按重量计含碳量 0.9% 至 1.15%、含铬量 0.5% 至 2%，若含钼则钼含量≤0.5%，呈不规则盘",e:"Bars and rods, hot-rolled, of steel containing by weight 0,9"},
    {c:"72279095",n:"合金钢热轧条杆（非不锈钢），呈不规则盘卷状（不包括高速钢、硅锰钢产品及税号 7227.90.10 和 7227.90.5",e:"Bars and rods, hot-rolled, in irregularly wound coils of all"},
    {c:"72281020",n:"高速钢条杆，仅经热轧、热拉拔或挤压（未进一步加工），以及经热轧、热拉拔或挤压并仅经包覆（未进一步加工）（不包括半成品、平",e:"Bars and rods of high-speed steel, not further worked than h"},
    {c:"72281050",n:"高速钢条杆，经锻造制得（不包括半成品、平板轧材及呈不规则盘卷状的热轧条杆）",e:"Bars and rods of high-speed steel, forged (excl. semi-finish"},
    {c:"72281090",n:"高速钢条杆，仅经冷加工成形或冷精整（无论是否进一步加工），或经热加工成形并进一步加工（不包括锻造产品、半成品、平板轧材及",e:"Bars and rods of high-speed steel, not further worked than c"},
    {c:"72282010",n:"硅锰钢条杆，截面为矩形（非方形），经四面热轧制得（不包括半成品、平板轧材及呈不规则盘卷状的热轧条杆）",e:"Bars and rods of silico-manganese steel, of rectangular \"oth"},
    {c:"72282091",n:"硅锰钢条杆，截面为方形或非矩形，仅经热轧、热拉拔或挤压（未进一步加工），以及经热轧、热拉拔或挤压并仅经包覆（未进一步加工",e:"Bars and rods of silico-manganese steel, of square or other "},
    {c:"72282099",n:"硅锰钢条杆，截面为方形或非矩形，仅经冷加工成形或冷精整（包括进一步加工的产品），或经热轧并进一步加工（不包括经热轧、热拉",e:"Bars and rods of silico-manganese stee, of square or other t"},
    {c:"72283020",n:"工具钢条杆，仅经热轧、热拉拔或挤压（未进一步加工）（不包括半成品、平板轧材及呈不规则盘卷状的热轧条杆）",e:"Bars and rods of tool steel, only hot-rolled, only hot-drawn"},
    {c:"72283041",n:"钢材条杆，按重量计含碳量 0.9% 至 1.15%、含铬量 0.5% 至 2%，若含钼则钼含量≤0.5%，仅经热轧、热拉",e:"Bars and rods of steel containing by weight 0,9 to 1,15% of "},
    {c:"72283049",n:"钢材条杆，按重量计含碳量 0.9% 至 1.15%、含铬量 0.5% 至 2%，若含钼则钼含量≤0.5%，仅经热轧、热拉",e:"Bars and rods of steel containing by weight 0,9 to 1,15% of "},
    {c:"72283061",n:"合金钢条杆（非不锈钢），仅经热轧、热拉拔或热挤压，截面为圆形且直径≥80 毫米（不包括高速钢、硅锰钢、工具钢产品及税号 ",e:"Bars and rods of alloy steel other than stainless steel, onl"},
    {c:"72283069",n:"合金钢条杆（非不锈钢），仅经热轧、热拉拔或热挤压，截面为圆形且直径＜80 毫米（不包括高速钢、硅锰钢、工具钢产品及税号 ",e:"Bars and rods or alloy steel other than stainless steel, onl"},
    {c:"72283070",n:"合金钢条杆（非不锈钢），截面为矩形（非方形），经四面热轧（不包括高速钢、硅锰钢、工具钢产品及税号 7228.30.41 ",e:"Bars and rods of alloy steel other than stainless steel, of "},
    {c:"72283089",n:"合金钢条杆（非不锈钢），仅经热轧、热拉拔或热挤压，截面为非矩形（非方形）且经四面轧制，或为圆形截面（不包括高速钢、硅锰钢",e:"Bars and rods of alloy steel other than stainless steel, onl"},
    {c:"72284010",n:"工具钢条杆，仅经锻造（不包括半成品、平板轧材及呈不规则盘卷状的热轧条杆）",e:"Bars and rods of tool steel, only forged (excl. semi-finishe"},
    {c:"72284090",n:"合金钢条杆（非不锈钢），仅经锻造（不包括高速钢、硅锰钢、工具钢产品，且不包括半成品、平板轧材及呈不规则盘卷状的热轧条杆）",e:"Bars and rods of alloy steel, other than stainless steel, on"},
    {c:"72285020",n:"工具钢条杆，仅经冷加工成形或冷精整（不包括半成品、平板轧材及呈不规则盘卷状的热轧条杆）",e:"Bars and rods of tool steel, only cold-formed or cold-finish"},
    {c:"72285040",n:"钢材条杆，按重量计含碳量 0.9% 至 1.15%、含铬量 0.5% 至 2%，若含钼则钼含量≤0.5%，仅经冷加工成形",e:"Bars and rods of steel containing 0,9% to 1,15% of carbon, 0"},
    {c:"72285061",n:"合金钢条杆（非不锈钢），仅经冷加工成形或冷精整（未进一步加工），截面为圆形且直径≥80 毫米（不包括高速钢、硅锰钢、工具",e:"Bars and rods of alloy steel, other than stainless steel, no"},
    {c:"72285069",n:"合金钢条杆（非不锈钢），仅经冷加工成形或冷精整（未进一步加工），截面为圆形且直径＜80 毫米（不包括高速钢、硅锰钢、工具",e:"Bars and rods of alloy steel, other than stainless steel, no"},
    {c:"72285080",n:"合金钢条杆（非不锈钢），仅经冷加工成形或冷精整（未进一步加工）（非圆形截面，不包括高速钢、硅锰钢、工具钢产品及税号 72",e:"Bars and rods of alloy steel, other than stainless steel, no"},
    {c:"72286020",n:"工具钢条杆，经冷加工成形或冷精整并进一步加工，或经热加工成形并进一步加工（不包括半成品、平板轧材及呈不规则盘卷状的热轧条",e:"Bars and rods of tool steel, cold-formed or cold-finished an"},
    {c:"72286080",n:"合金钢条杆（非不锈钢），经冷加工成形或冷精整并进一步加工，或经热加工成形并进一步加工（不包括高速钢、硅锰钢、工具钢条杆，",e:"Bars and rods of alloy steel, other than stainless steel, co"},
    {c:"72287010",n:"合金钢角材、型材及异型材（非不锈钢），仅经热轧、热拉拔或挤压（未进一步加工）",e:"Angles, shapes and sections of alloy steel other than stainl"},
    {c:"72287090",n:"合金钢角材、型材及异型材（非不锈钢），其他未列名的（不包括仅经热轧、热拉拔或挤压的产品）",e:"Angles, shapes and sections of alloy steel other than stainl"},
    {c:"72288000",n:"合金或非合金钢空心钻杆",e:"Hollow drill bars and rods, of alloy or non-alloy steel"},
    {c:"72292000",n:"硅锰钢线材，呈盘卷状（不包括条杆）",e:"Wire of silico-manganese steel, in coils (excl. bars and rod"},
    {c:"72299020",n:"高速钢线材，呈盘卷状（不包括条杆）",e:"Wire of high-speed steel, in coils (excl. bars and rods)"},
    {c:"72299050",n:"钢材线材，按重量计含碳量 0.9% 至 1.1%、含铬量 0.5% 至 2%，若含钼则钼含量≤0.5%，呈盘卷状（不包括",e:"Wire of steel containing by weight 0,9% to 1,1% of carbon, 0"},
    {c:"72299090",n:"合金钢线材（非不锈钢），呈盘卷状（不包括轧制条杆、高速钢或硅锰钢线材及税号 7229.90.50 的商品）",e:"Wire of alloy steel other than stainless, in coils (excl. ro"},
    {c:"73011000",n:"钢铁板桩，无论是否钻孔、冲孔或由组装件制成",e:"Sheet piling of iron or steel, whether or not drilled, punch"},
    {c:"73012000",n:"钢铁角材、型材及异型材，经焊接制得",e:"Angles, shapes and sections, of iron or steel, welded"},
    {c:"73021010",n:"钢铁导电轨，带有有色金属部件，用于铁路或电车轨道（不包括护轨）",e:"Current-conducting rails of iron or steel, with parts of non"},
    {c:"73021022",n:"钢铁槽型轨，全新，用于铁路或电车轨道，每米重量≥36 千克",e:"Vignole rails of iron or steel, for railway or tramway track"},
    {c:"73021028",n:"钢铁槽型轨，全新，用于铁路或电车轨道，每米重量＜36 千克",e:"Vignole rails of iron or steel, for railway or tramway track"},
    {c:"73021040",n:"钢铁槽形轨，全新，用于铁路或电车轨道",e:"Grooved rails of iron or steel, for railway or tramway track"},
    {c:"73021050",n:"钢铁轨道，全新，用于铁路或电车轨道（不包括槽型轨、槽形轨及带有有色金属部件的导电轨）",e:"Rails of iron or steel, for railway or tramway track, new (e"},
    {c:"73021090",n:"钢铁轨道，二手，用于铁路或电车轨道（不包括带有有色金属部件的导电轨）",e:"Rails of iron or steel, for railway or tramway track, used ("},
    {c:"73023000",n:"钢铁道岔尖轨、辙叉、转辙杆及其他道岔配件，用于铁路或电车轨道",e:"Switch blades, crossing frogs, point rods and other crossing"},
    {c:"73024000",n:"钢铁鱼尾板及底板，用于铁路或电车轨道",e:"Fish-plates and sole plates of iron or steel, for railways o"},
    {c:"73029000",n:"钢铁轨枕（交叉枕木）、护轨、齿轨、轨座、轨座楔、轨卡、垫板及连接件，以及其他用于铁路或电车轨道连接或固定的专用材料（不包",e:"Sleepers \"cross-ties\", check-rails, rack rails, chairs, chai"},
    {c:"73030010",n:"铸铁制压力系统用管",e:"Tubes and pipes of a kind used in pressure systems, of cast "},
    {c:"73030090",n:"铸铁制管、导管及空心型材（不包括压力系统用产品）",e:"Tubes, pipes and hollow profiles, of cast iron (excl. produc"},
    {c:"73041100",n:"不锈钢无缝管线管，用于石油或天然气输送管道",e:"Line pipe of a kind used for oil or gas pipelines, seamless,"},
    {c:"73041910",n:"钢铁无缝管线管，用于石油或天然气输送管道，外径≤168.3 毫米（不包括不锈钢或铸铁制品）",e:"Line pipe of a kind used for oil or gas pipelines, seamless,"},
    {c:"73041930",n:"钢铁无缝管线管，用于石油或天然气输送管道，外径＞168.3 毫米但≤406.4 毫米（不包括不锈钢或铸铁制品）",e:"Line pipe of a kind used for oil or gas pipelines, seamless,"},
    {c:"73041990",n:"钢铁无缝管线管，用于石油或天然气输送管道，外径＞406.4 毫米（不包括不锈钢或铸铁制品）",e:"Line pipe of a kind used for oil or gas pipelines, seamless,"},
    {c:"73042200",n:"不锈钢无缝钻杆，用于石油或天然气钻探",e:"Drill pipe, seamless, of stainless steel, of a kind used in "},
    {c:"73042300",n:"钢铁无缝钻杆，用于石油或天然气钻探（不包括不锈钢或铸铁制品）",e:"Drill pipe, seamless, of a kind used in drilling for oil or "},
    {c:"73042400",n:"不锈钢无缝套管和油管，用于石油或天然气钻探",e:"Casing and tubing, seamless, of a kind used for drilling for"},
    {c:"73042910",n:"钢铁无缝套管和油管，用于石油或天然气钻探，外径≤168.3 毫米（不包括铸铁制品）",e:"Casing and tubing of a kind used for drilling for oil or gas"},
    {c:"73042930",n:"钢铁无缝套管和油管，用于石油或天然气钻探，外径＞168.3 毫米但≤406.4 毫米（不包括铸铁制品）",e:"Casing and tubing of a kind used for drilling for oil or gas"},
    {c:"73042990",n:"钢铁无缝套管和油管，用于石油或天然气钻探，外径＞406.4 毫米（不包括铸铁制品）",e:"Casing and tubing of a kind used for drilling for oil or gas"},
    {c:"73043120",n:"铁或非合金钢无缝精密管，截面为圆形，经冷拉拔或冷轧（冷压延）制得（不包括石油或天然气输送用管线管及石油或天然气钻探用套管",e:"Precision tubes, seamless, of circular cross-section, of iro"},
    {c:"73043180",n:"铁或非合金钢无缝管、导管及空心型材，截面为圆形，经冷拉拔或冷轧（冷压延）制得（不包括铸铁制品、石油或天然气输送用管线管、",e:"Tubes, pipes and hollow profiles, seamless, of circular cros"},
    {c:"73043950",n:"铁或非合金钢无缝螺纹或可螺纹化管（煤气管）（不包括铸铁制品）",e:"Threaded or threadable tubes \"gas pipe\", seamless, of iron o"},
    {c:"73043982",n:"铁或非合金钢无缝管、导管及空心型材，截面为圆形，外径≤168.3 毫米（不包括经冷拉拔或冷轧的产品、铸铁制品、石油或天然",e:"Tubes, pipes and hollow profiles, seamless, of circular cros"},
    {c:"73043983",n:"铁或非合金钢无缝管、导管及空心型材，截面为圆形，外径＞168.3 毫米但≤406.4 毫米（不包括经冷拉拔或冷轧的产品、",e:"Tubes, pipes and hollow profiles, seamless, of circular cros"},
    {c:"73043988",n:"铁或非合金钢无缝管、导管及空心型材，截面为圆形，外径＞406.4 毫米（不包括经冷拉拔或冷轧的产品、铸铁制品、石油或天然",e:"Tubes, pipes and hollow profiles, seamless, of circular cros"},
    {c:"73044100",n:"不锈钢无缝管、导管及空心型材，截面为圆形，经冷拉拔或冷轧（冷压延）制得（不包括石油或天然气输送用管线管及石油或天然气钻探",e:"Tubes, pipes and hollow profiles, seamless, of circular cros"},
    {c:"73044983",n:"不锈钢无缝管、导管及空心型材，截面为圆形，外径≤168.3 毫米（不包括经冷拉拔或冷轧的产品、石油或天然气输送用管线管及",e:"Tubes, pipes and hollow profiles, seamless, of circular cros"},
    {c:"73044985",n:"不锈钢无缝管、导管及空心型材，截面为圆形，外径＞168.3 毫米但≤406.4 毫米（不包括经冷拉拔或冷轧的产品、石油或",e:"Tubes, pipes and hollow profiles, seamless, of circular cros"},
    {c:"73044989",n:"不锈钢无缝管、导管及空心型材，截面为圆形，外径＞406.4 毫米（不包括经冷拉拔或冷轧的产品、石油或天然气输送用管线管及",e:"Tubes, pipes and hollow profiles, seamless, of circular cros"},
    {c:"73045110",n:"合金钢无缝管、导管及空心型材（非不锈钢），截面为圆形，经冷拉拔或冷轧（冷压延）制得，直形且壁厚均匀，按重量计含碳量≥0.",e:"Tubes, pipes and hollow profiles, seamless, of circular cros"},
    {c:"73045181",n:"合金钢无缝精密管（非不锈钢），截面为圆形，经冷拉拔或冷轧（冷压延）制得（不包括石油或天然气输送用管线管、石油钻探用套管和",e:"Precision tubes, seamless, of circular cross-section, of all"},
    {c:"73045189",n:"合金钢无缝管、导管及空心型材（非不锈钢），截面为圆形，未经冷拉拔或冷轧（冷压延）制得（不包括石油或天然气输送用管线管、石",e:"Tubes, pipes and hollow profiles, seamless, of circular cros"},
    {c:"73045930",n:"合金钢无缝管、导管及空心型材（非不锈钢），截面为圆形（未经冷拉拔或冷轧），直形且壁厚均匀，按重量计含碳量≥0.9% 但≤",e:"Tubes, pipes and hollow profiles of alloy steel (excl. stain"},
    {c:"73045982",n:"合金钢无缝管、导管及空心型材（非不锈钢），截面为圆形，外径≤168.3 毫米（不包括经冷拉拔或冷轧的产品、石油或天然气输",e:"Tubes, pipes and hollow profiles, seamless, of circular cros"},
    {c:"73045983",n:"合金钢无缝管、导管及空心型材（非不锈钢），截面为圆形，外径＞168.3 毫米但≤406.4 毫米（不包括经冷拉拔或冷轧的",e:"Tubes, pipes and hollow profiles, seamless, of circular cros"},
    {c:"73045989",n:"合金钢无缝管、导管及空心型材（非不锈钢），截面为圆形，外径＞406.4 毫米（不包括经冷拉拔或冷轧的产品、石油或天然气输",e:"Tubes, pipes and hollow profiles, seamless, of circular cros"},
    {c:"73049000",n:"钢铁无缝管、导管及空心型材，截面为非圆形（不包括铸铁制品）",e:"Tubes, pipes and hollow profiles, seamless, of non-circular "},
    {c:"73051100",n:"钢铁管线管，用于石油或天然气输送管道，截面为圆形且外径＞406.4 毫米，经纵向埋弧焊制得",e:"Line pipe of a kind used for oil or gas pipelines, having ci"},
    {c:"73051200",n:"钢铁管线管，用于石油或天然气输送管道，截面为圆形且外径＞406.4 毫米，经纵向弧焊制得（不包括经纵向埋弧焊的产品）",e:"Line pipe of a kind used for oil or gas pipelines, having ci"},
    {c:"73051900",n:"钢铁平板轧材制管线管，用于石油或天然气输送管道，截面为圆形且外径＞406.4 毫米（不包括经纵向弧焊的产品）",e:"Line pipe of a kind used for oil or gas pipelines, having ci"},
    {c:"73052000",n:"钢铁平板轧材制套管，用于石油或天然气钻探，截面为圆形且外径＞406.4 毫米",e:"Casing of a kind used in drilling for oil or gas, having cir"},
    {c:"73053100",n:"钢铁管及导管，截面为圆形且外径＞406.4 毫米，经纵向焊接制得（不包括石油或天然气输送用及石油或天然气钻探用产品）",e:"Tubes and pipes having circular cross-sections and an extern"},
    {c:"73053900",n:"钢铁管及导管，截面为圆形且外径＞406.4 毫米，经焊接制得（不包括经纵向焊接的产品、石油或天然气输送用及石油或天然气钻",e:"Tubes and pipes having circular cross-sections and an extern"},
    {c:"73059000",n:"钢铁平板轧材制管及导管，截面为圆形且外径＞406.4 毫米，经焊接制得（不包括焊接产品、石油或天然气输送用及石油或天然气",e:"Tubes and pipes having circular cross-sections and an extern"},
    {c:"73061100",n:"不锈钢平板轧材制焊接管线管，用于石油或天然气输送管道，外径≤406.4 毫米",e:"Line pipe of a kind used for oil or gas pipelines, welded, o"},
    {c:"73061900",n:"钢铁平板轧材制焊接管线管，用于石油或天然气输送管道，外径≤406.4 毫米（不包括不锈钢或铸铁制品）",e:"Line pipe of a kind used for oil or gas pipelines, welded, o"},
    {c:"73062100",n:"不锈钢平板轧材制焊接套管和油管，用于石油或天然气钻探，外径≤406.4 毫米",e:"Casing and tubing of a kind used in drilling for oil or gas,"},
    {c:"73062900",n:"钢铁平板轧材制焊接套管和油管，用于石油或天然气钻探，外径≤406.4 毫米（不包括不锈钢或铸铁制品）",e:"Casing and tubing of a kind used in drilling for oil or gas,"},
    {c:"73063012",n:"铁或非合金钢焊接精密管，截面为圆形，经冷拉拔或冷轧（冷压延）制得",e:"Precision tubes, welded, of circular cross-section, of iron "},
    {c:"73063018",n:"铁或非合金钢焊接精密管，截面为圆形（不包括经冷拉拔或冷轧的产品）",e:"Precision tubes, welded, of circular cross-section, of iron "},
    {c:"73063041",n:"铁或非合金钢焊接螺纹或可螺纹化管（煤气管），截面为圆形，经镀锌处理",e:"Threaded or threadable tubes \"gas pipe\", welded, of circular"},
    {c:"73063049",n:"铁或非合金钢焊接螺纹或可螺纹化管（煤气管），截面为圆形（不包括经镀锌处理的产品）",e:"Threaded or threadable tubes \"gas pipe\", welded, of circular"},
    {c:"73063072",n:"其他铁或非合金钢焊接管、导管及空心型材，截面为圆形，外径≤168.3 毫米，经镀锌处理（不包括石油或天然气输送用管线管及",e:"Other tubes, pipes and hollow profiles, welded, of circular "},
    {c:"73063077",n:"其他铁或非合金钢焊接管、导管及空心型材，截面为圆形，外径≤168.3 毫米（不包括经镀锌处理的产品、石油或天然气输送用管",e:"Other tubes, pipes and hollow profiles, welded, of circular "},
    {c:"73063080",n:"钢铁焊接管、导管及空心型材，截面为圆形，外径＞168.3 毫米但≤406.4 毫米（不包括石油或天然气输送用管线管、石油",e:"Tubes, pipes and hollow profiles, welded, having a circular "},
    {c:"73064020",n:"不锈钢焊接管、导管及空心型材，截面为圆形，经冷拉拔或冷轧（冷压延）制得（不包括内外截面均为圆形且外径＞406.4 毫米的",e:"Tubes, pipes and hollow profiles, welded, of circular cross-"},
    {c:"73064080",n:"不锈钢焊接管、导管及空心型材，截面为圆形（不包括经冷拉拔或冷轧的产品、内外截面均为圆形且外径＞406.4 毫米的产品、石",e:"Tubes, pipes and hollow profiles, welded, of circular cross-"},
    {c:"73065021",n:"合金钢焊接钢制精密管（非不锈钢），截面为圆形，经冷拉拔或冷轧（冷压延）制得",e:"Precision steel tubes, welded, of circular cross-section, of"},
    {c:"73065029",n:"合金钢焊接钢制精密管（非不锈钢），截面为圆形（不包括经冷拉拔或冷轧的产品）",e:"Precision steel tubes, welded, of circular cross-section, of"},
    {c:"73065080",n:"合金钢焊接管、导管及空心型材（非不锈钢），截面为圆形（不包括内外截面均为圆形且外径＞406.4 毫米的管及导管、石油或天",e:"Tubes, pipes and hollow profiles, welded, of circular cross-"},
    {c:"73066110",n:"不锈钢焊接管、导管及空心型材，截面为方形或矩形",e:"Tubes and pipes and hollow profiles, welded, of square or re"},
    {c:"73066192",n:"非不锈钢焊接管、导管及空心型材，截面为方形或矩形，壁厚≤2 毫米",e:"Tubes and pipes and hollow profiles, welded, of square or re"},
    {c:"73066199",n:"非不锈钢焊接管、导管及空心型材，截面为方形或矩形，壁厚＞2 毫米",e:"Tubes and pipes and hollow profiles, welded, of square or re"},
    {c:"73066910",n:"不锈钢焊接管、导管及空心型材，截面为非圆形（不包括内外截面均为圆形且外径＞406.4 毫米的管及导管、石油或天然气输送用",e:"Tubes, pipes and hollow profiles, welded, of non-circular cr"},
    {c:"73066990",n:"非不锈钢焊接管、导管及空心型材，截面为非圆形（不包括内外截面均为圆形且外径＞406.4 毫米的管及导管、石油或天然气输送",e:"Tubes, pipes and hollow profiles, welded, of non-circular cr"},
    {c:"73069000",n:"钢铁管、导管及空心型材（如开缝管、铆接或类似封闭方式的管）（不包括铸铁制品、无缝或焊接管及导管，以及内外截面均为圆形且外",e:"Tubes, pipes and hollow profiles \"e.g., open seam, riveted o"},
    {c:"73071110",n:"不可锻铸铁制管件，用于压力系统",e:"Tube or pipe fittings of non-malleable cast iron, of a kind "},
    {c:"73071190",n:"不可锻铸铁制管件（不包括用于压力系统的产品）",e:"Tube or pipe fittings of non-malleable cast iron (excl. prod"},
    {c:"73071910",n:"铸铁制管件（不包括不可锻铸铁制品）",e:"Tube or pipe fittings of cast iron (excl. of non-malleable)"},
    {c:"73071990",n:"钢制铸造管件",e:"Cast tube or pipe fittings of steel"},
    {c:"73072100",n:"不锈钢法兰（不包括铸造产品）",e:"Flanges of stainless steel (excl. cast products)"},
    {c:"73072210",n:"不锈钢螺纹套管（不包括铸造产品）",e:"Sleeves, of stainless steel, threaded (excl. cast products)"},
    {c:"73072290",n:"不锈钢螺纹弯头和弯管（不包括铸造产品）",e:"Elbows and bends, of stainless steel, threaded (excl. cast p"},
    {c:"73072310",n:"不锈钢对焊弯头和弯管（不包括铸造产品）",e:"Butt welding elbows and bends of stainless steel (excl. cast"},
    {c:"73072390",n:"不锈钢对焊管件（不包括铸造产品及弯头和弯管）",e:"Butt welding tube or pipe fittings of stainless steel (excl."},
    {c:"73072910",n:"不锈钢螺纹管件（不包括铸造产品、法兰、弯头、弯管及套管）",e:"Threaded tube or pipe fittings of stainless steel (excl. cas"},
    {c:"73072980",n:"不锈钢管件（不包括铸造、螺纹、对焊管件及法兰）",e:"Tube or pipe fittings of stainless steel (excl. cast, thread"},
    {c:"73079100",n:"钢铁法兰（不包括铸造或不锈钢品）",e:"Flanges of iron or steel (excl. cast or stainless products)"},
    {c:"73079210",n:"钢铁螺纹套管（不包括铸造或不锈钢品）",e:"Sleeves of iron or steel, threaded (excl. cast or of stainle"},
    {c:"73079290",n:"钢铁螺纹弯头和弯管（不包括铸造或不锈钢品）",e:"Elbows and bends, of iron or steel, threaded (excl. cast or "},
    {c:"73079311",n:"钢铁对焊弯头和弯管，最大外径≤609.6 毫米（不包括铸铁或不锈钢品）",e:"Butt welding elbows and bends, of iron or steel, with greate"},
    {c:"73079319",n:"钢铁对焊管件，最大外径≤609.6 毫米（不包括铸铁或不锈钢品、弯头、弯管及法兰）",e:"Butt welding fittings of iron or steel, with greatest extern"},
    {c:"73079391",n:"钢铁对焊弯头和弯管，最大外径＞609.6 毫米（不包括铸铁或不锈钢品）",e:"Butt welding elbows and bends, of iron or steel, with greate"},
    {c:"73079399",n:"钢铁对焊管件，最大外径＞609.6 毫米（不包括铸铁或不锈钢品、弯头、弯管及法兰）",e:"Butt welding fittings of iron or steel, with greatest extern"},
    {c:"73079910",n:"钢铁螺纹管件（不包括铸铁或不锈钢品、法兰、弯头、弯管及套管）",e:"Threaded tube or pipe fittings, of iron or steel (excl. cast"},
    {c:"73079980",n:"钢铁管件（不包括铸铁或不锈钢品、螺纹、对焊管件及法兰）",e:"Tube or pipe fittings, of iron or steel (excl. of cast iron "},
    {c:"73081000",n:"钢铁桥梁及桥梁构件",e:"Bridges and bridge-sections, of iron or steel"},
    {c:"73082000",n:"钢铁塔及格构式桅杆",e:"Towers and lattice masts, of iron or steel"},
    {c:"73083000",n:"钢铁门、窗及其框架和门槛",e:"Doors, windows and their frames and thresholds for doors, of"},
    {c:"73084000",n:"钢铁脚手架、模板、支撑或坑式支撑用设备（不包括复合板桩产品及具有模具特征的现浇混凝土用模板）",e:"Equipment for scaffolding, shuttering, propping or pit-propp"},
    {c:"73089051",n:"钢铁夹芯板，由两层波纹（肋状）钢板构成且带有绝缘芯材",e:"Panels comprising two walls of profiled \"ribbed\" sheet, of i"},
    {c:"73089059",n:"钢铁结构件及其部件，仅由或主要由钢板制成，其他未列名的（不包括门、窗及其框架，以及钢铁两层波纹（肋状）钢板夹芯绝缘板）",e:"Structures and parts of structures, of iron or steel, solely"},
    {c:"73089098",n:"钢铁结构件及其部件，其他未列名的（不包括桥梁及桥梁构件、塔、格构式桅杆、门、窗及其框架和门槛、脚手架 / 模板 / 支撑",e:"Structures and parts of structures of iron or steel, n.e.s. "},
    {c:"73090010",n:"钢铁储罐、槽、桶及类似容器，用于储存非压缩或液化气体，容量＞300 升（不包括装有机械或热力设备的容器及专为一种或多种运",e:"Reservoirs, tanks, vats and similar containers, of iron or s"},
    {c:"73090030",n:"钢铁储罐、槽、桶及类似容器，用于储存液体，带衬里或隔热层且容量＞300 升（不包括装有机械或热力设备的容器及专为一种或多",e:"Reservoirs, tanks, vats and similar containers, of iron or s"},
    {c:"73090051",n:"钢铁储罐、槽、桶及类似容器，用于储存液体，容量＞100000 升（不包括带衬里 / 隔热层、装有机械或热力设备的容器及专",e:"Reservoirs, tanks, vats and similar containers, of iron or s"},
    {c:"73090059",n:"钢铁储罐、槽、桶及类似容器，用于储存液体，容量≤100000 升但＞300 升（不包括带衬里 / 隔热层、装有机械或热力",e:"Reservoirs, tanks, vats and similar containers, of iron or s"},
    {c:"73090090",n:"钢铁储罐、槽、桶及类似容器，用于储存固体，容量＞300 升（不包括带衬里 / 隔热层、装有机械或热力设备的容器及专为一种",e:"Reservoirs, tanks, vats and similar containers, of iron or s"},
    {c:"73101000",n:"钢铁罐、桶、鼓、罐、箱及类似容器，用于装载各类物料，容量≥50 升但≤300 升，其他未列名的（不包括压缩或液化气体用容",e:"Tanks, casks, drums, cans, boxes and similar containers, of "},
    {c:"73102111",n:"钢铁罐，容量＜50 升，需通过钎焊或压接密封，用于食品保鲜",e:"Cans of iron or steel, of a capacity of < 50 l, which are to"},
    {c:"73102119",n:"钢铁罐，容量＜50 升，需通过钎焊或压接密封，用于饮品保鲜",e:"Cans of iron or steel, of a capacity of < 50 l, which are to"},
    {c:"73102191",n:"钢铁罐，容量＜50 升，需通过钎焊或压接密封，壁厚＜0.5 毫米（不包括压缩或液化气体用罐、食品及饮品保鲜用罐）",e:"Cans of iron or steel, of a capacity of < 50 l, which are to"},
    {c:"73102199",n:"钢铁罐，容量＜50 升，需通过钎焊或压接密封，壁厚≥0.5 毫米（不包括压缩或液化气体用罐、食品及饮品保鲜用罐）",e:"Cans of iron or steel, of a capacity of < 50 l, which are to"},
    {c:"73102910",n:"钢铁罐、桶、鼓、罐、箱及类似容器，用于装载各类物料，容量＜50 升且壁厚＜0.5 毫米，其他未列名的（不包括压缩或液化气",e:"Tanks, casks, drums, cans, boxes and similar containers, of "},
    {c:"73102990",n:"钢铁罐、桶、鼓、罐、箱及类似容器，用于装载各类物料，容量＜50 升且壁厚≥0.5 毫米，其他未列名的（不包括压缩或液化气",e:"Tanks, casks, drums, cans, boxes and similar containers, of "},
    {c:"73110011",n:"钢铁无缝容器，用于储存压缩或液化气体，承压≥165 巴，容量＜20 升（不包括专为一种或多种运输方式设计的容器）",e:"Containers of iron or steel, seamless, for compressed or liq"},
    {c:"73110013",n:"钢铁无缝容器，用于储存压缩或液化气体，承压≥165 巴，容量≥20 升且≤50 升（不包括专为一种或多种运输方式设计的容",e:"Containers of iron or steel, seamless, for compressed or liq"},
    {c:"73110019",n:"钢铁无缝容器，用于储存压缩或液化气体，承压≥165 巴，容量＞50 升（不包括专为一种或多种运输方式设计的容器）",e:"Containers of iron or steel, seamless, for compressed or liq"},
    {c:"73110030",n:"钢铁无缝容器，用于储存压缩或液化气体，承压＜165 巴（不包括专为一种或多种运输方式设计的容器）",e:"Containers of iron or steel, seamless, for compressed or liq"},
    {c:"73110091",n:"钢铁容器，用于储存压缩或液化气体，容量＜1000 升（不包括无缝容器及专为一种或多种运输方式设计的容器）",e:"Containers of iron or steel, seamless, for compressed or liq"},
    {c:"73110099",n:"钢铁容器，用于储存压缩或液化气体，容量≥1000 升（不包括无缝容器及专为一种或多种运输方式设计的容器）",e:"Containers of iron or steel, seamless, for compressed or liq"},
    {c:"73181100",n:"钢铁方头木螺钉",e:"Coach screws of iron or steel"},
    {c:"73181210",n:"不锈钢木螺钉（不包括方头木螺钉）",e:"Wood screws of stainless steel (excl. coach screws)"},
    {c:"73181290",n:"非不锈钢木螺钉（不包括方头木螺钉）",e:"Wood screws of iron or steel other than stainless (excl. coa"},
    {c:"73181300",n:"钢铁螺钉钩和螺钉环",e:"Screw hooks and screw rings, of iron or steel"},
    {c:"73181410",n:"不锈钢自攻螺钉（不包括木螺钉）",e:"Self-tapping screws, of stainless steel (excl. wood screws)"},
    {c:"73181491",n:"非不锈钢间隔螺纹螺钉",e:"Spaced-thread screws of iron or steel other than stainless"},
    {c:"73181499",n:"非不锈钢自攻螺钉（不包括间隔螺纹螺钉及木螺钉）",e:"Self-tapping screws of iron or steel other than stainless (e"},
    {c:"73181520",n:"钢铁螺钉和螺栓（无论是否配有螺母和垫圈），用于固定铁路轨道建筑材料（不包括方头木螺钉）",e:"Screws and bolts, of iron or steel \"whether or not with thei"},
    {c:"73181535",n:"不锈钢无头螺钉和螺栓（无论是否配有螺母和垫圈）（不包括用于固定铁路轨道建筑材料的螺钉和螺栓）",e:"Screws and bolts, of stainless steel \"whether or not with th"},
    {c:"73181542",n:"非不锈钢无头螺钉和螺栓（无论是否配有螺母和垫圈），抗拉强度＜800 兆帕（不包括用于固定铁路轨道建筑材料的螺钉和螺栓）",e:"Screws and bolts, of iron or steel other than stainless \"whe"},
    {c:"73181548",n:"非不锈钢无头螺钉和螺栓（无论是否配有螺母和垫圈），抗拉强度≥800 兆帕（不包括用于固定铁路轨道建筑材料的螺钉和螺栓）",e:"Screws and bolts, of iron or steel other than stainless \"whe"},
    {c:"73181552",n:"不锈钢一字槽或十字槽头螺钉和螺栓（无论是否配有螺母和垫圈）（不包括木螺钉及自攻螺钉）",e:"Screws and bolts, of stainless steel \"whether or not with th"},
    {c:"73181558",n:"非不锈钢一字槽或十字槽头螺钉和螺栓（无论是否配有螺母和垫圈）（不包括木螺钉及自攻螺钉）",e:"Screws and bolts, of iron or steel other than stainless \"whe"},
    {c:"73181562",n:"不锈钢内六角头螺钉和螺栓（无论是否配有螺母和垫圈）（不包括木螺钉、自攻螺钉及用于固定铁路轨道建筑材料的螺钉和螺栓）",e:"Hexagonal-socket head screws and bolts, of stainless steel \""},
    {c:"73181568",n:"非不锈钢内六角头螺钉和螺栓（无论是否配有螺母和垫圈）（不包括木螺钉、自攻螺钉及用于固定铁路轨道建筑材料的螺钉和螺栓）",e:"Hexagonal-socket head screws and bolts, of iron or steel oth"},
    {c:"73181575",n:"不锈钢六角头螺钉和螺栓（无论是否配有螺母和垫圈）（不包括内六角头、木螺钉、自攻螺钉及用于固定铁路轨道建筑材料的螺钉和螺栓",e:"Hexagon screws and bolts, of stainless steel \"whether or not"},
    {c:"73181582",n:"非不锈钢六角头螺钉和螺栓（无论是否配有螺母和垫圈），抗拉强度＜800 兆帕（不包括内六角头、木螺钉、自攻螺钉及用于固定铁",e:"Hexagon screws and bolts, of iron or steel other than stainl"},
    {c:"73181588",n:"非不锈钢六角头螺钉和螺栓（无论是否配有螺母和垫圈），抗拉强度≥800 兆帕（不包括内六角头、木螺钉、自攻螺钉及用于固定铁",e:"Hexagon screws and bolts, of iron or steel other than stainl"},
    {c:"73181595",n:"钢铁带头部螺钉和螺栓（无论是否配有螺母和垫圈）（不包括一字槽、十字槽或六角头的产品；木螺钉、自攻螺钉、用于固定铁路轨道建",e:"Screws and bolts, of iron or steel \"whether or not with thei"},
    {c:"73181631",n:"不锈钢盲铆螺母",e:"Blind rivet nuts of stainless steel"},
    {c:"73181639",n:"不锈钢螺母（不包括盲铆螺母）",e:"Nuts of stainless steel (excl. blind rivet nuts)"},
    {c:"73181640",n:"非不锈钢盲铆螺母",e:"Blind rivet nuts of iron or steel other than stainless"},
    {c:"73181660",n:"非不锈钢自锁螺母",e:"Self-locking nuts of iron or steel other than stainless"},
    {c:"73181692",n:"非不锈钢螺母，内径≤12 毫米（不包括盲铆螺母及自锁螺母）",e:"Nuts of iron or steel other than stainless, with an inside d"},
    {c:"73181699",n:"非不锈钢螺母，内径＞12 毫米（不包括盲铆螺母及自锁螺母）",e:"Nuts of iron or steel other than stainless, with an inside d"},
    {c:"73181900",n:"钢铁螺纹制品，其他未列名的",e:"Threaded articles, of iron or steel, n.e.s."},
    {c:"73182100",n:"钢铁弹簧垫圈及其他防松垫圈",e:"Spring washers and other lock washers, of iron or steel"},
    {c:"73182200",n:"钢铁垫圈（不包括弹簧垫圈及其他防松垫圈）",e:"Washers of iron or steel (excl. spring washers and other loc"},
    {c:"73182300",n:"钢铁铆钉（不包括特殊用途的管状铆钉和开叉铆钉）",e:"Rivets of iron or steel (excl. tubular and bifurcated rivets"},
    {c:"73182400",n:"钢铁扁销及开尾销",e:"Cotters and cotter pins, of iron or steel"},
    {c:"73182900",n:"钢铁非螺纹制品",e:"Non-threaded articles, of iron or steel"},
    {c:"73261100",n:"钢铁磨球及其他磨机用类似制品，经锻造或冲压但未进一步加工",e:"Grinding balls and similar articles for mills, of iron or st"},
    {c:"73261910",n:"钢铁开模锻件，未进一步加工，其他未列名的（不包括磨球及其他磨机用类似制品）",e:"Articles of iron or steel, open-die forged, but not further "},
    {c:"73261990",n:"钢铁闭模锻件或冲压件，未进一步加工，其他未列名的（不包括磨球及其他磨机用类似制品）",e:"Articles of iron or steel, closed-die forged or stamped, but"},
    {c:"73262000",n:"钢铁丝制制品，其他未列名的",e:"Articles of iron or steel wire, n.e.s."},
    {c:"73269030",n:"钢铁梯子及阶梯",e:"Ladders and steps, of iron or steel"},
    {c:"73269040",n:"钢铁托盘及其他货物搬运用类似平台",e:"Pallets and similar platforms for handling goods, of iron or"},
    {c:"73269050",n:"钢铁电缆、管道等用卷轴",e:"Reels for cables, piping and the like, of iron or steel"},
    {c:"73269060",n:"钢铁非机械通风设备、檐槽、挂钩及其他建筑行业用类似制品，其他未列名的",e:"Ventilators, non-mechanical, guttering, hooks and like artic"},
    {c:"73269092",n:"钢铁开模锻件，其他未列名的",e:"Articles of iron or steel, open-die forged, n.e.s."},
    {c:"73269094",n:"钢铁闭模锻件，其他未列名的",e:"Articles of iron or steel, closed-die forged, n.e.s."},
    {c:"73269096",n:"钢铁烧结制品，其他未列名的",e:"Sintered articles of iron or steel, n.e.s."},
    {c:"73269098",n:"钢铁制品，其他未列名的",e:"Articles of iron or steel, n.e.s."},
    {c:"76011010",n:"非合金铝扁锭，未锻轧",e:"Aluminium slabs, not alloyed, unwrought"},
    {c:"76011090",n:"非合金铝，未锻轧（不包括扁锭）",e:"Aluminium, not alloyed, unwrought (excl. slabs)"},
    {c:"76012030",n:"铝合金扁锭，未锻轧",e:"Unwrought aluminium alloys in the form of slabs"},
    {c:"76012040",n:"铝合金坯料，未锻轧",e:"Unwrought aluminium alloys in the form of billets"},
    {c:"76012080",n:"铝合金，未锻轧（不包括扁锭及坯料）",e:"Unwrought aluminium alloys (excl. slabs and billets)"},
    {c:"76031000",n:"铝粉，非片状结构（不包括铝丸）",e:"Powders of aluminium, of non-lamellar structure (excl. pelle"},
    {c:"76032000",n:"铝粉，片状结构；铝箔碎片（不包括铝丸及铝亮片）",e:"Powders of aluminium, of lamellar structure, and flakes of a"},
    {c:"76041010",n:"非合金铝条、杆及型材",e:"Bars, rods and profiles, of non-alloy aluminium"},
    {c:"76041090",n:"非合金铝型材，其他未列名的",e:"Profiles of non-alloy aluminium, n.e.s."},
    {c:"76042100",n:"铝合金空心型材，其他未列名的",e:"Hollow profiles of aluminium alloys, n.e.s."},
    {c:"76042910",n:"铝合金条、杆",e:"Bars and rods of aluminium alloys"},
    {c:"76042990",n:"铝合金实心型材，其他未列名的",e:"Solid profiles, of aluminium alloys, n.e.s."},
    {c:"76051100",n:"非合金铝丝，最大横截面尺寸＞7 毫米（不包括绞合线、电缆、编织带等及税目 7614 的其他制品、绝缘电线）",e:"Wire of non-alloy aluminium, with a maximum cross-sectional "},
    {c:"76051900",n:"非合金铝丝，最大横截面尺寸≤7 毫米（不包括绞合线、电缆、绳索及税目 7614 的其他制品、绝缘电线、乐器用弦）",e:"Wire of non-alloy aluminium, with a maximum cross-sectional "},
    {c:"76052100",n:"铝合金丝，最大横截面尺寸＞7 毫米（不包括绞合线、电缆、编织带等及税目 7614 的其他制品、绝缘电线）",e:"Wire of aluminium alloys, with a maximum cross-sectional dim"},
    {c:"76052900",n:"铝合金丝，最大横截面尺寸≤7 毫米（不包括绞合线、电缆、绳索及税目 7614 的其他制品、绝缘电线、乐器用弦）",e:"Wire, of aluminium alloys, having a maximum cross-sectional "},
    {c:"76061130",n:"非合金铝复合板，厚度＞0.2 毫米",e:"Aluminium Composite Panel, of non-alloy aluminium, of a thic"},
    {c:"76061150",n:"非合金铝板、片及带，厚度＞0.2 毫米，方形或矩形，经涂漆、清漆涂覆或塑料涂层处理（不包括铝复合板）",e:"Plates, sheets and strip, of non-alloy aluminium, of a thick"},
    {c:"76061191",n:"非合金铝板、片及带，厚度＞0.2 毫米但＜3 毫米，方形或矩形（不包括经涂漆、清漆涂覆或塑料涂层处理的产品及发泡板、片和",e:"Plates, sheets and strip, of non-alloy aluminium, of a thick"},
    {c:"76061193",n:"非合金铝板、片及带，厚度≥3 毫米但＜6 毫米，方形或矩形（不包括经涂漆、清漆涂覆或塑料涂层处理的产品）",e:"Plates, sheets and strip, of non-alloy aluminium, of a thick"},
    {c:"76061199",n:"非合金铝板、片及带，厚度≥6 毫米，方形或矩形（不包括经涂漆、清漆涂覆或塑料涂层处理的产品）",e:"Plates, sheets and strip, of non-alloy aluminium, of a thick"},
    {c:"76061211",n:"铝合金制饮料罐罐身坯料，厚度＞0.2 毫米",e:"Beverage can body stock, of aluminium alloys, of a thickness"},
    {c:"76061219",n:"铝合金制饮料罐罐盖坯料及拉环坯料，厚度＞0.2 毫米",e:"Beverage can end stock and tab stock, of aluminium alloys, o"},
    {c:"76061230",n:"铝合金复合板，厚度＞0.2 毫米",e:"Aluminium Composite Panel, of aluminium alloys, of a thickne"},
    {c:"76061250",n:"铝合金板、片及带，厚度＞0.2 毫米，方形或矩形，经涂漆、清漆涂覆或塑料涂层处理（不包括饮料罐罐身坯料、罐盖坯料、拉环坯",e:"Plates, sheets and strip, of aluminium alloys, of a thicknes"},
    {c:"76061292",n:"铝合金板、片及带，厚度＞0.2 毫米但＜3 毫米，方形或矩形（不包括经涂漆、清漆涂覆或塑料涂层处理的产品、发泡板片带及饮",e:"Plates, sheets and strip, of aluminium alloys, of a thicknes"},
    {c:"76061293",n:"铝合金板、片及带，厚度≥3 毫米但＜6 毫米，方形或矩形（不包括经涂漆、清漆涂覆或塑料涂层处理的产品）",e:"Plates, sheets and strip, of aluminium alloys, of a thicknes"},
    {c:"76061299",n:"铝合金板、片及带，厚度≥6 毫米，方形或矩形（不包括经涂漆、清漆涂覆或塑料涂层处理的产品）",e:"Plates, sheets and strip, of aluminium alloys, of a thicknes"},
    {c:"76069100",n:"非合金铝板、片及带，厚度＞0.2 毫米（非方形或矩形）",e:"Plates, sheets and strip, of non-alloy aluminium, of a thick"},
    {c:"76069200",n:"铝合金板、片及带，厚度＞0.2 毫米（非方形或矩形）",e:"Plates, sheets and strip, of aluminium alloys, of a thicknes"},
    {c:"76071111",n:"无衬背铝箔，经轧制但未进一步加工，厚度＜0.021 毫米，成卷且重量≤10 千克（不包括税目 3212 的烫印箔及制成圣",e:"Aluminium foil, not backed, rolled but not further worked, o"},
    {c:"76071119",n:"无衬背铝箔，经轧制但未进一步加工，厚度＜0.021 毫米（不包括税目 3212 的烫印箔、制成圣诞树装饰材料的铝箔及成卷",e:"Aluminium foil, not backed, rolled but not further worked, o"},
    {c:"76071190",n:"无衬背铝箔，经轧制但未进一步加工，厚度≥0.021 毫米且≤2 毫米（不包括税目 3212 的烫印箔及制成圣诞树装饰材料",e:"Aluminium foil, not backed, rolled but not further worked, o"},
    {c:"76071910",n:"无衬背铝箔，经轧制并进一步加工，厚度＜0.021 毫米（不包括税目 3212 的烫印箔及制成圣诞树装饰材料的铝箔）",e:"Aluminium foil, not backed, rolled and further worked, of a "},
    {c:"76071990",n:"无衬背铝箔，经轧制并进一步加工，厚度（不含衬背）0.021 毫米至 0.2 毫米（不包括税目 3212 的烫印箔及制成圣",e:"Aluminium foil, not backed, rolled and further worked, of a "},
    {c:"76072010",n:"有衬背铝箔，厚度（不含衬背）＜0.021 毫米（不包括税目 3212 的烫印箔及制成圣诞树装饰材料的铝箔）",e:"Aluminium foil, backed, of a thickness (excl. any backing) o"},
    {c:"76072091",n:"铝复合板，厚度≤0.2 毫米",e:"Aluminium Composite Panel, of a thickness <= 0,2 mm"},
    {c:"76072099",n:"有衬背铝箔，厚度（不含衬背）≥0.021 毫米且≤0.2 毫米（不包括税目 3212 的烫印箔、制成圣诞树装饰材料的铝箔",e:"Aluminium foil, backed, of a thickness (excl. any backing) o"},
    {c:"76081000",n:"非合金铝管及导管（不包括空心型材）",e:"Tubes and pipes of non-alloy aluminium (excl. hollow profile"},
    {c:"76082020",n:"铝合金焊接管及导管（不包括空心型材）",e:"Tubes and pipes of aluminium alloys, welded (excl. hollow pr"},
    {c:"76082081",n:"铝合金管及导管，仅经挤压加工（未进一步加工）（不包括空心型材）",e:"Tubes and pipes of aluminium alloys, not further worked than"},
    {c:"76082089",n:"铝合金管及导管（不包括焊接产品、仅经挤压加工的产品及空心型材）",e:"Tubes and pipes of aluminium alloys (excl. such products wel"},
    {c:"76090000",n:"铝制管件（如管接头、弯头、套管）",e:"Aluminium tube or pipe fittings \"e.g., couplings, elbows, sl"},
    {c:"76101000",n:"铝制门、窗及其框架和门槛（不包括门用五金件）",e:"Doors, windows and their frames and thresholds for door, of "},
    {c:"76109010",n:"铝制桥梁及桥梁构件、塔及格构式桅杆",e:"Bridges and bridge-sections, towers and lattice masts, of al"},
    {c:"76109090",n:"铝制结构件及其部件，其他未列名的；铝制板、杆、型材、管等，经加工供结构用，其他未列名的（不包括税目 9406 的预制建筑",e:"Structures and parts of structures, of aluminium, n.e.s., an"},
    {c:"76110000",n:"铝制储罐、槽、桶及类似容器，用于装载除压缩或液化气体外的各类物料，容量＞300 升，未配备机械或热力设备，无论是否带衬里",e:"Reservoirs, tanks, vats and similar containers, of aluminium"},
    {c:"76121000",n:"铝制可伸缩管状容器",e:"Collapsible tubular containers, of aluminium"},
    {c:"76129020",n:"铝制气雾剂用容器",e:"Containers of a kind used for aerosols, of aluminium"},
    {c:"76129030",n:"铝制桶、鼓、罐、箱及类似容器，由厚度≤0.2 毫米的铝箔制成",e:"Casks, drums, cans, boxes and similar containers, of alumini"},
    {c:"76129080",n:"铝制桶、鼓、罐、箱及类似容器，容量≤300 升，用于装载除压缩或液化气体外的各类物料，其他未列名的（不包括可伸缩管状容器",e:"Casks, drums, cans, boxes and similar containers <= 300 l, o"},
    {c:"76130000",n:"铝制压缩或液化气体用容器",e:"Aluminium containers for compressed or liquefied gas"},
    {c:"76141000",n:"铝制绞合线、电缆、编织带等，带钢芯（不包括绝缘产品）",e:"Stranded wire, cables, plaited bands and the like, of alumin"},
    {c:"76149000",n:"铝制绞合线、电缆、绳索及类似制品（不带钢芯，且不包括绝缘产品）",e:"Stranded wires, cables, ropes and similar articles, of alumi"},
    {c:"76161000",n:"铝制钉、平头钉、订书钉、螺钉、螺栓、螺母、螺钉钩、铆钉、扁销、开尾销、垫圈及类似制品（不包括成条订书钉、螺纹塞、塞子及类",e:"Nails, tacks, staples, screws, bolts, nuts, screw hooks, riv"},
    {c:"76169100",n:"铝丝制布、格栅、网及围栏（不包括服装、衬里及类似用途的金属纤维布，以及制成手工筛或机器零件的布、格栅和网）",e:"Cloth, grill, netting and fencing, of aluminium wire (excl. "},
    {c:"76169910",n:"铝制铸造制品，其他未列名的",e:"Articles of aluminium, cast, n.e.s."},
    {c:"76169990",n:"铝制非铸造制品，其他未列名的",e:"Articles of aluminium, uncast, n.e.s."},
    {c:"73121069",n:"非不锈钢制钢铁绞线，最大横截面尺寸大于 3 毫米，带涂层（不含电气绝缘产品、绞合围栏用线及带刺铁丝网，以及镀锌镀层或涂层",e:"Stranded wire, of iron or steel other than stainless, with a"},
    {c:"73121081",n:"非不锈钢制钢铁绳索（含密封钢丝绳），最大横截面尺寸大于 3 毫米但不大于 12 毫米，无涂层或仅镀锌镀层 / 涂层（不含",e:"Ropes and cables, incl. locked-coil ropes, of iron or steel "},
    {c:"73121083",n:"非不锈钢制钢铁绳索（含密封钢丝绳），最大横截面尺寸大于 12 毫米但不大于 24 毫米，无涂层或仅镀锌镀层 / 涂层（不",e:"Ropes and cables, incl. locked-coil ropes, of iron or steel "},
    {c:"73121085",n:"非不锈钢制钢铁绳索（含密封钢丝绳），最大横截面尺寸大于 24 毫米但不大于 48 毫米，无涂层或仅镀锌镀层 / 涂层（不",e:"Ropes and cables, incl. locked-coil ropes, of iron or steel "},
    {c:"73121020",n:"不锈钢制绞线、绳索（含密封钢丝绳）（不含电气绝缘产品、绞合围栏用线及带刺铁丝网）",e:"Stranded wire, ropes and cables, of stainless steel (excl. e"},
    {c:"73121041",n:"非不锈钢制钢铁绞线、绳索（含密封钢丝绳），最大横截面尺寸不大于 3 毫米，镀铜锌合金（黄铜）镀层 / 涂层（不含电气绝缘",e:"Stranded wire, ropes and cables, of iron or steel other than"},
    {c:"73121089",n:"非不锈钢制钢铁绳索（含密封钢丝绳），最大横截面尺寸大于 48 毫米，无涂层或仅镀锌镀层 / 涂层（不含电气绝缘产品、绞合",e:"Ropes and cables, incl. locked-coil ropes, of iron or steel "},
    {c:"73121098",n:"非不锈钢制钢铁绳索（含密封钢丝绳），最大横截面尺寸大于 3 毫米（不含无涂层或仅镀锌镀层 / 涂层的产品、电气绝缘产品、",e:"Ropes and cables, incl. locked-coil ropes, of iron or steel "},
    {c:"73121049",n:"非不锈钢制钢铁绞线、绳索（含密封钢丝绳），最大横截面尺寸不大于 3 毫米（不含电气绝缘产品、绞合围栏用线及带刺铁丝网，以",e:"Stranded wire, ropes and cables, of iron or steel other than"},
    {c:"73121061",n:"非不锈钢制钢铁绞线，无涂层，最大横截面尺寸大于 3 毫米（不含电气绝缘产品、绞合围栏用线及带刺铁丝网）",e:"Stranded wire, of iron or steel other than stainless, uncoat"},
    {c:"73121065",n:"非不锈钢制钢铁绞线，最大横截面尺寸大于 3 毫米，镀锌镀层 / 涂层（不含电气绝缘产品、绞合围栏用线及带刺铁丝网）",e:"Stranded wire, of iron or steel other than stainless, with a"},
    {c:"73143900",n:"钢铁丝焊接交叉格栅、网及围栏（不含最大横截面尺寸不小于 3 毫米且网孔尺寸不小于 100 平方厘米的产品，以及镀锌镀层 ",e:"Grill, netting and fencing, of iron or steel wire, welded at"},
    {c:"73202089",n:"钢铁制螺旋弹簧（不含热加工制品、螺旋压缩弹簧及螺旋拉伸弹簧）",e:"Helical springs, of iron or steel (excl. hot-worked, coil co"},
    {c:"73209090",n:"钢铁制弹簧及弹簧片（不含碟形弹簧、平面涡卷弹簧、螺旋弹簧、板簧及其弹簧片、钟表用弹簧、雨伞或阳伞柄用弹簧，以及第 17 ",e:"Springs and leaves for springs, of iron or steel (excl. disc"},
    {c:"73239400",n:"非铸铁制铁或非不锈钢制钢搪瓷家用器具（含厨房或其他家用）及其零件（不含 7310 章的罐、盒及类似容器；废纸篓；铁锹、开",e:"Table, kitchen or other household articles, and parts thereo"},
    {c:"73239900",n:"非铸铁制铁或非不锈钢制钢家用器具（含厨房或其他家用）及其零件（不含搪瓷制品；7310 章的罐、盒及类似容器；废纸篓；铁锹",e:"Table, kitchen or other household articles, and parts thereo"},
    {c:"73259100",n:"铸造磨机用研磨球及类似制品（不含不可锻铸铁制此类制品）",e:"Grinding balls and similar articles for mills, cast (excl. s"},
    {c:"73259910",n:"其他未列名铸铁制品（不含不可锻铸铁制制品及磨机用研磨球及类似制品）",e:"Articles of cast iron, n.e.s. (excl. of non-malleable cast i"},
    {c:"73259990",n:"其他未列名铸钢制品（不含磨机用研磨球及类似制品）",e:"Articles of cast steel, n.e.s. (excl. grinding balls and sim"},
    {c:"73251000",n:"其他未列名不可锻铸铁制品",e:"Articles of non-malleable cast iron, n.e.s."},
    {c:"73143100",n:"其他钢铁丝焊接交叉格栅、网及围栏，镀锌镀层 / 涂层",e:"Other grill, netting and fencing, of iron or steel wire, wel"},
    {c:"73144100",n:"钢铁丝非焊接交叉格栅、网及围栏，镀锌镀层 / 涂层",e:"Grill, netting and fencing, of iron or steel wire, not welde"},
    {c:"73144900",n:"钢铁丝非焊接交叉格栅、网及围栏（不含镀锌镀层 / 涂层或塑料涂层的产品）",e:"Grill, netting and fencing, of iron or steel wire, not welde"},
    {c:"73170060",n:"钢铁丝制钉子、平头钉、瓦楞钉、订书钉及类似制品（不含成条或成卷的钉子及订书钉）",e:"Nails, tacks, corrugated nails, staples and similar articles"},
    {c:"73170080",n:"钢铁制钉子、平头钉、图钉、瓦楞钉、订书钉及类似制品（不含钢丝冷压制成的产品及成条订书钉）",e:"Nails, tacks, drawing pins, corrugated nails, staples and si"},
    {c:"73170020",n:"成条或成卷的钢铁丝制钉子",e:"Nails of iron or steel wire, in strips or coils"},
    {c:"74151000",n:"铜制或钢铁制（铜制钉头）钉子、平头钉、图钉、订书钉及类似制品（含钢或铝）",e:"Nails, tacks,drawing pins, staples and similar articles, of "},
    {c:"83024200",n:"其他适用于家具的贱金属连接件、配件及类似制品（含钢或铝）",e:"Other base metal mountings, fittings and similar articles su"},
    {c:"83024900",n:"其他贱金属连接件、配件及类似制品（含钢或铝）",e:"Other base metal mountings, fittings and similar articles, c"},
    {c:"83099090",n:"其他贱金属塞子、盖子（含螺旋盖、倾注塞、瓶用胶囊、带螺纹塞、塞盖、密封件及其他贱金属包装附件）（含钢或铝）",e:"Other stoppers, caps and lids, (including screw caps and pou"},
    {c:"84082010",n:"压燃式活塞内燃机（柴油或半柴油发动机），用于以下产品的工业装配：子目 8701.10 的手扶拖拉机、品目 8703 的机",e:"Compressionignition internal combustion piston engine (diese"},
    {c:"84082051",n:"压燃式活塞内燃机（柴油或半柴油发动机），用于 87 章机动车辆，功率不超过 50 千瓦",e:"Compressionignition internal combustion piston engine (diese"},
    {c:"84082055",n:"压燃式活塞内燃机（柴油或半柴油发动机），用于 87 章机动车辆，功率超过 50 千瓦但不超过 100 千瓦",e:"Compressionignition internal combustion piston engine (diese"},
    {c:"84082057",n:"压燃式活塞内燃机（柴油或半柴油发动机），用于 87 章机动车辆，功率超过 100 千瓦但不超过 200 千瓦",e:"Compressionignition internal combustion piston engine (diese"},
    {c:"84082099",n:"压燃式活塞内燃机（柴油或半柴油发动机），用于 87 章机动车辆，功率超过 200 千瓦",e:"Compressionignition internal combustion piston engine (diese"},
    {c:"84089065",n:"新压燃式活塞内燃机（柴油或半柴油发动机），功率超过 200 千瓦但不超过 300 千瓦",e:"Compressionignition internal combustion piston engine (diese"},
    {c:"84089067",n:"新压燃式活塞内燃机（柴油或半柴油发动机），功率超过 300 千瓦但不超过 500 千瓦",e:"Compressionignition internal combustion piston engine (diese"},
    {c:"84133020",n:"活塞内燃机用喷射泵",e:"Injection pumps for internal combustion piston engine"},
    {c:"84133080",n:"活塞内燃机用燃油、润滑油或冷却液泵（不含喷射泵）",e:"Fuel, lubricating or cooling medium pumps for internal combu"},
    {c:"84137035",n:"其他离心泵，排出口直径不超过 15 毫米",e:"Other centrifugal pumps, with a discharge outlet diameter no"},
    {c:"84161010",n:"液体燃料炉用燃烧器，带自动控制装置",e:"Furnace burners for liquid fuel, incorporating an automatic "},
    {c:"84161090",n:"液体燃料炉用燃烧器（不含带自动控制装置的产品）",e:"Furnace burners for liquid fuel (excl. those incorporating a"},
    {c:"84162020",n:"煤粉或气体用组合式炉燃烧器",e:"Combination furnace burners for pulverised solid fuel or for"},
    {c:"84162080",n:"煤粉固体燃料或气体用炉燃烧器（不含仅用于气体的、整体式且配备通风机和控制装置的产品及组合式燃烧器）",e:"Furnace burners for pulverised solid fuel or gas (excl. such"},
    {c:"84162010",n:"仅用于气体的炉用燃烧器，整体式，配备通风机和控制装置",e:"Furnace burners, only for gas, monobloc, incorporating a ven"},
    {c:"84169000",n:"炉燃烧器、机械加煤机零件（含机械炉篦、机械出灰器及类似设备）（含钢或铝）",e:"Parts of furnace burners, mechanical stokers, including thei"},
    {c:"84181020",n:"组合式冷藏冷冻箱，容量超过 340 升，配备独立外门、抽屉或其组合",e:"Combined refrigerator-freezers, of a capacity > 340 l, fitte"},
    {c:"84181080",n:"组合式冷藏冷冻箱，容量不超过 340 升，配备独立外门、抽屉或其组合",e:"Combined refrigerator-freezers, of a capacity <= 340 l, fitt"},
    {c:"84189990",n:"制冷或冷冻设备及热泵零件（含钢或铝）",e:"Parts of refrigerating or freezing equipment and heat pumps,"},
    {c:"84198910",n:"冷却塔及类似直接冷却（无隔墙）设备，采用循环水冷却",e:"Cooling towers and similar plant for direct cooling (without"},
    {c:"84198998",n:"其他未列名机器、设备及装置",e:"Other machinery, plant and equipment"},
    {c:"84199085",n:"机器、设备或实验室设备零件（含钢或铝）",e:"Parts of machinery, plant or laboratory equipment, containin"},
    {c:"84209110",n:"压延机或其他滚轧机用滚筒，铸铁制（不含用于金属或玻璃加工的滚筒）",e:"Cylinders for calendering or other rolling machines, of cast"},
    {c:"84209180",n:"压延机或其他滚轧机用滚筒（不含铸铁制及用于金属或玻璃加工的滚筒）",e:"Cylinders for calendering or other rolling machines (excl. o"},
    {c:"84212300",n:"活塞内燃机用机油或汽油滤清器（含钢或铝）",e:"Oil or petrolfilters for internal combustion engines, contai"},
    {c:"84243001",n:"带内置电机的净水设备，配备加热装置",e:"Water cleaning appliances with built-in motor, with heating "},
    {c:"84243008",n:"带内置电机的净水设备，未配备加热装置",e:"Water cleaning appliances with built-in motor, without heati"},
    {c:"84243010",n:"蒸汽或喷砂设备及类似喷射机，压缩空气驱动",e:"Steam or sand blasting machines and similar jet projecting m"},
    {c:"84243090",n:"蒸汽或喷砂设备及类似喷射机（不含压缩空气驱动的产品、带内置电机的净水设备及专用容器清洗设备）",e:"Steam or sand blasting machines and similar jet projecting m"},
    {c:"84248210",n:"农业或园艺用灌溉设备（含钢或铝）",e:"Agricultural or horticultural watering appliances, containin"},
    {c:"84248970",n:"其他未列名液体或粉末喷射、分散或喷雾用机械设备（无论是否手动操作）（含钢或铝）",e:"Mechanical appliances, whether or not hand-operated, for pro"},
    {c:"84248940",n:"液体或粉末喷射、分散或喷雾用机械设备，专用于或主要用于印刷电路或印刷电路组件制造（含钢或铝）",e:"Mechanical appliances for projecting, dispersing, or sprayin"},
    {c:"84249020",n:"专用于或主要用于印刷电路或印刷电路组件制造的液体或粉末喷射、分散或喷雾用机械设备零件（含钢或铝）",e:"Parts of mechanical appliances for projecting, dispersing, o"},
    {c:"84249080",n:"灭火器、喷枪及类似设备、蒸汽或喷砂设备及类似喷射机、其他未列名液体或粉末喷射、分散或喷雾用机械设备零件（含钢或铝）",e:"Parts of fire extinguishers, spray guns and similar applianc"},
    {c:"84253100",n:"电动卷扬机及绞盘",e:"Winches and capstans powered by electric motor"},
    {c:"84253900",n:"其他卷扬机及绞盘",e:"Other winches and capstans"},
    {c:"84254200",n:"其他千斤顶及起重机，液压式，用于车辆举升",e:"Other jacks and hoists, hydraulic of a kind used for raising"},
    {c:"84261900",n:"其他桥式起重机、搬运起重机、门式起重机及移动式起重架",e:"Other overhead travelling cranes, transporter cranes, gantry"},
    {c:"84269900",n:"其他船用吊杆；起重机（含缆索起重机）；移动式起重架、跨运车及装有起重机的工程车辆",e:"Other Ships' derricks; cranes, including cable cranes; mobil"},
    {c:"84279000",n:"其他装有起重或装卸设备的工程车辆，非自行式",e:"Other works trucks fitted with lifting or handling equipment"},
    {c:"84282020",n:"气动升降及输送设备，用于散装物料",e:"Pneumatic elevators and conveyors, for bulk materials"},
    {c:"84282080",n:"气动升降及输送设备（不含用于散装物料的设备）",e:"Pneumatic elevators and conveyors (excl. those for bulk mate"},
    {c:"84283300",n:"连续式货物或物料升降及输送设备，带式",e:"Continuous-action elevators and conveyors for goods or mater"},
    {c:"84283990",n:"其他连续式货物或物料升降及输送设备",e:"Other Continuous-action elevators and conveyors for goods or"},
    {c:"84287000",n:"工业机器人",e:"Industrial robots"},
    {c:"84289090",n:"其他未列名起重、搬运、装卸机械",e:"Lifting, handling, loading or unloading machinery, n.e.s."},
    {c:"84289071",n:"专用于农用拖拉机装配的装载机",e:"Loaders specially designed for attachment to agricultural tr"},
    {c:"84289079",n:"农用装载机（不含专用于农用拖拉机装配的装载机）",e:"Loaders for use in agriculture (excl. those specially design"},
    {c:"84306100",n:"夯实或压实机械，非自行式",e:"Tamping or compacting machinery, not self-propelled"},
    {c:"84306900",n:"其他机械，非自行式",e:"Other machinery, not self-propelled"},
    {c:"84311000",n:"8425 章机械零件（滑轮组及起重机（不含料斗式起重机）、卷扬机、绞盘及千斤顶）（含钢或铝）",e:"Parts of machinery of heading 8425 (pulley tackles and hoist"},
    {c:"84312000",n:"8427 章机械零件（叉车及其他装有起重或装卸设备的工程车辆）（含钢或铝）",e:"Parts of machinery of heading 8427 (fork-lift trucks and oth"},
    {c:"84313100",n:"电梯、料斗式起重机或自动扶梯零件（含钢或铝）",e:"Parts of lifts, skip hoists or escalators, containing steel "},
    {c:"84313900",n:"8428 章机械其他零件（含钢或铝）",e:"Other parts of machinery of heading 8428, containing steel o"},
    {c:"84314920",n:"8426、8429 及 8430 章机械其他未列名零件，铸铁或铸钢制",e:"Parts of machinery of heading 8426, 8429 and 8430 of cast ir"},
    {c:"84314980",n:"8426、8429 及 8430 章机械其他未列名零件",e:"Parts of machinery of heading 8426, 8429 and 8430, n.e.s."},
    {c:"84328000",n:"其他农业、园艺或林业用土壤准备或耕作机械；草坪或运动场滚压机",e:"Other agricultural, horticultural or forestry machinery for "},
    {c:"84329000",n:"农业、园艺或林业用土壤准备或耕作机械及草坪或运动场滚压机零件",e:"Parts of agricultural, horticultural or forestry machinery f"},
    {c:"84501111",n:"全自动家用或洗衣店用前开门式洗衣机，干衣容量不超过 6 千克",e:"Fully-automatic household or laundry-type front-loading wash"},
    {c:"84501119",n:"全自动家用或洗衣店用顶开门式洗衣机，干衣容量不超过 6 千克",e:"Fully-automatic household or laundry-type top-loading washin"},
    {c:"84501190",n:"全自动家用或洗衣店用洗衣机，干衣容量超过 6 千克但不超过 10 千克",e:"Fully-automatic household or laundry-type washing machines, "},
    {c:"84501200",n:"带内置离心脱水机的洗衣机",e:"type washing machines, with built-in centrifugal drier"},
    {c:"84501900",n:"其他家用或洗衣店用洗衣机，干衣容量不超过 10 千克",e:"Other household or laundry-type washing machines, of a dry l"},
    {c:"84512100",n:"干衣容量不超过 10 千克的烘干机",e:"Drying machines, of a dry linen capacity not exceeding 10 kg"},
    {c:"84541000",n:"冶金或金属铸造用转炉",e:"Converters of a kind used in metallurgy or in metal foundrie"},
    {c:"84542000",n:"冶金或金属铸造用钢锭模及浇包",e:"Ingot moulds and ladles, of a kind used in metallurgy or in "},
    {c:"84543010",n:"冶金或金属铸造用压力铸造机",e:"Machines for casting under pressure of a kind used in metall"},
    {c:"84543090",n:"冶金或金属铸造用铸造机（不含压力铸造机）",e:"Casting machines of a kind used in metallurgy or in metal fo"},
    {c:"84641000",n:"锯床",e:"Sawing machines"},
    {c:"84649000",n:"其他石材、陶瓷、混凝土、石棉水泥或类似矿物材料加工机床及玻璃冷加工机床",e:"Other machine tools for working stones, ceramics, concrete, "},
    {c:"84741000",n:"固体（含粉末或膏状）形式的土壤、石料、矿石或其他矿物分选、筛选、分离或洗涤设备",e:"Sorting, screening, separating or washing machines for earth"},
    {c:"84742000",n:"固体（含粉末或膏状）形式的土壤、石料、矿石或其他矿物破碎或研磨设备",e:"Crushing or grinding machines for earth, stone, ores or othe"},
    {c:"84743900",n:"其他固体（含粉末或膏状）形式的土壤、石料、矿石或其他矿物混合或捏合设备",e:"Other mixing or kneading machines for earth, stone, ores or "},
    {c:"84791000",n:"公共工程、建筑或类似用途机械",e:"Machinery for public works, building or the like"},
    {c:"84805000",n:"玻璃用模具（含铁）",e:"Moulds for glass, containing iron"},
    {c:"85013200",n:"直流电动机、直流发电机，输出功率超过 750 瓦但不超过 75 千瓦（不含光伏发电机）",e:"DC motors, DC generators of an output exceeding 750 W but no"},
    {c:"85015381",n:"多相交流电动机，输出功率超过 75 千瓦但不超过 375 千瓦",e:"AC motors, multiphase, of an output of exceeding 75 kW but n"},
    {c:"85043180",n:"其他变压器，额定容量不超过 1 千伏安",e:"Other transformers having a power handling capacity not exce"},
    {c:"85043300",n:"其他变压器，额定容量超过 16 千伏安但不超过 500 千伏安",e:"Other transformers having a power handling capacity exceedin"},
    {c:"85045000",n:"电感器（含钢或铝）",e:"Inductors, containing steel or aluminium"},
    {c:"85153990",n:"其他金属电弧焊接设备（含等离子弧焊接设备）",e:"Other machines and apparatus for arc welding of metals, incl"},
    {c:"85441110",n:"电气用铜制绕组线，漆包或瓷漆包（含钢或铝）",e:"Winding wire for electrical purposes, of copper, lacquered o"},
    {c:"85441190",n:"电气用铜制绕组线，绝缘（不含漆包或瓷漆包）（含钢或铝）",e:"Winding wire for electrical purposes, of copper, insulated ("},
    {c:"85441900",n:"电气用非铜制绕组线，绝缘（含钢或铝）",e:"Winding wire for electrical purposes, of material other than"},
    {c:"85444920",n:"电压≤80 伏的绝缘导电体，不带连接器，其他未列名电信用途（含钢或铝）",e:"Conductors, electric, for a voltage <= 80 V, insulated, not "},
    {c:"85444991",n:"电压≤1000 伏的绝缘电线电缆，不带连接器，其他未列名，单根导体直径超过 0.51 毫米（含钢或铝）",e:"Electric wire and cables, for a voltage <= 1.000 V, insulate"},
    {c:"85444993",n:"电压≤80 伏的绝缘导电体，不带连接器，其他未列名（不含绕组线、同轴导体、车辆 / 航空器 / 船舶用布线组件及单根导体",e:"Conductors, electric, for a voltage <= 80 V, insulated, not "},
    {c:"85444995",n:"电压 > 80 伏但 < 1000 伏的绝缘导电体，不带连接器，其他未列名（不含绕组线、同轴导体、车辆 / 航空器 / ",e:"Electric conductors for a voltage > 80 V but < 1.000 V, insu"},
    {c:"85444999",n:"电压 1000 伏的绝缘导电体，不带连接器，其他未列名（不含绕组线、同轴导体、车辆 / 航空器 / 船舶用布线组件及单根",e:"Electric conductors for a voltage 1.000 V, insulated, not fi"},
    {c:"85446010",n:"电压 > 1000 伏的绝缘导电体，铜制导体，其他未列名（含钢或铝）",e:"Electric conductors for a voltage > 1.000 V, insulated, with"},
    {c:"85446090",n:"电压 > 1000 伏的绝缘导电体，非铜制导体，其他未列名（含钢或铝）",e:"Electric conductors for a voltage > 1.000 V, insulated, not "},
    {c:"87042110",n:"运输高放射性物质的机动车 [欧共体原子能共同体]，仅以压燃式活塞内燃机（柴油或半柴油发动机）为驱动，车辆总质量≤5 吨（",e:"Motor vehicles for the transport of highly radioactive mater"},
    {c:"87042131",n:"货运机动车，仅以压燃式活塞内燃机（柴油或半柴油发动机）为驱动，车辆总质量≤5 吨，气缸容量 > 2500 立方厘米，新车",e:"Motor vehicles for the transport of goods, with only compres"},
    {c:"87042191",n:"货运机动车，仅以压燃式活塞内燃机（柴油或半柴油发动机）为驱动，车辆总质量≤5 吨，气缸容量≤2500 立方厘米，新车（不",e:"Motor vehicles for the transport of goods, with only compres"},
    {c:"87042210",n:"运输高放射性物质的机动车 [欧共体原子能共同体]，仅以压燃式活塞内燃机（柴油或半柴油发动机）为驱动，车辆总质量 > 5 ",e:"Motor vehicles, with only compression-ignition internal comb"},
    {c:"87042291",n:"货运机动车，仅以压燃式活塞内燃机（柴油或半柴油发动机）为驱动，车辆总质量 > 5 吨但≤20 吨，新车（不含子目 870",e:"Motor vehicles for the transport of goods, with only compres"},
    {c:"87042310",n:"车辆总质量超过 20 吨的机动车（不含 8704.2399 子目所列产品）（含钢或铝）",e:"Motor vehicles of a gross vehicle weight exceeding 20 tonnes"},
    {c:"87043131",n:"货运机动车，仅以点燃式活塞内燃机为驱动，车辆总质量≤5 吨，气缸容量 > 2800 立方厘米，新车（不含子目 87041",e:"Motor vehicles for the transport of goods, with only spark-i"},
    {c:"87043191",n:"货运机动车，仅以点燃式活塞内燃机为驱动，车辆总质量≤5 吨，气缸容量≤2800 立方厘米，新车（不含子目 870410 ",e:"Motor vehicles for the transport of goods, with only spark-i"},
    {c:"87043110",n:"运输高放射性物质的机动车 [欧共体原子能共同体]，仅以点燃式活塞内燃机为驱动，车辆总质量≤5 吨（含钢或铝）",e:"Motor vehicles, with only spark-ignition internal combustion"},
    {c:"87043210",n:"车辆总质量超过 5 吨的机动车，仅以点燃式活塞内燃机为驱动（不含 8704.3299 子目所列产品）（含钢或铝）",e:"Motor vehicles, with only sparkignition internal combustion "},
    {c:"87044110",n:"运输高放射性物质的机动车 [欧共体原子能共同体]，以压燃式活塞内燃机（柴油或半柴油发动机）和电动机为驱动电机，车辆总质量",e:"Motor vehicles, with both compression-ignition internal comb"},
    {c:"87044131",n:"货运机动车，以压燃式活塞内燃机（柴油或半柴油发动机）和电动机为驱动电机，车辆总质量≤5 吨，气缸容量 > 2500 立方",e:"Motor vehicles for the transport of goods, with both compres"},
    {c:"87044191",n:"货运机动车，以压燃式活塞内燃机（柴油或半柴油发动机）和电动机为驱动电机，车辆总质量≤5 吨，气缸容量≤2500 立方厘米",e:"Motor vehicles for the transport of goods, with both compres"},
    {c:"87044210",n:"运输高放射性物质的机动车 [欧共体原子能共同体]，以压燃式活塞内燃机（柴油或半柴油发动机）和电动机为驱动电机，车辆总质量",e:"Motor vehicles, with both compression-ignition internal comb"},
    {c:"87044291",n:"货运机动车，以压燃式活塞内燃机（柴油或半柴油发动机）和电动机为驱动电机，车辆总质量 > 5 吨但≤20 吨，新车（不含子",e:"Motor vehicles for the transport of goods, with both compres"},
    {c:"87044391",n:"货运机动车，以压燃式活塞内燃机（柴油或半柴油发动机）和电动机为驱动电机，车辆总质量 > 20 吨，新车（不含子目 870",e:"Motor vehicles for the transport of goods, with both compres"},
    {c:"87044310",n:"运输高放射性物质的机动车 [欧共体原子能共同体]，以压燃式活塞内燃机（柴油或半柴油发动机）和电动机为驱动电机，车辆总质量",e:"Motor vehicles, with both compression-ignition internal comb"},
    {c:"87046000",n:"货运机动车，仅以电动机为驱动电机",e:"Motor vehicles for the transport of goods, with only electri"},
    {c:"87049000",n:"其他货运机动车",e:"Other motor vehicles for the transport of goods"},
    {c:"87060099",n:"底盘，配备压燃式活塞内燃机（气缸容量≤2500 立方厘米）或点燃式活塞内燃机（气缸容量≤2800 立方厘米），用于 10",e:"Chassis with compression ignition internal combustion engine"},
    {c:"87060011",n:"底盘，配备压燃式活塞内燃机（气缸容量 > 2500 立方厘米）或点燃式活塞内燃机（气缸容量 > 2800 立方厘米），用",e:"Chassis with compression ignition internal combustion engine"},
    {c:"87060019",n:"底盘，配备压燃式活塞内燃机（气缸容量 > 2500 立方厘米）或点燃式活塞内燃机（气缸容量 > 2800 立方厘米），用",e:"Chassis with compression ignition internal combustion engine"},
    {c:"87060091",n:"底盘，配备压燃式活塞内燃机（气缸容量≤2500 立方厘米）或点燃式活塞内燃机（气缸容量≤2800 立方厘米），用于轿车及",e:"Chassis with compression ignition internal combustion engine"},
    {c:"87071090",n:"轿车及其他主要设计用于载客的机动车用车身（不含子目 87071010 所列用于工业装配的车身）",e:"Bodies for motor cars and other motor vehicles principally d"},
    {c:"87071010",n:"用于轿车及其他主要设计用于载客的机动车工业装配的车身",e:"Bodies for the industrial assembly of motor cars and other m"},
    {c:"87084020",n:"变速箱及其零件，用于以下产品的工业装配：手扶拖拉机、轿车及其他主要设计用于载客的机动车、配备压燃式活塞内燃机（柴油或半柴",e:"Gear boxes and parts thereof, for the industrial assembly of"},
    {c:"87084050",n:"变速箱，用于拖拉机、10 人及以上载客机动车、轿车及其他主要设计用于载客的机动车、货运机动车及专用机动车（不含子目 87",e:"Gear boxes for tractors, motor vehicles for the transport of"},
    {c:"87084091",n:"变速箱零件，闭模锻钢制，用于拖拉机、10 人及以上载客机动车、轿车及其他主要设计用于载客的机动车、货运机动车及其他未列名",e:"Parts for gear boxes of closed-die forged steel, for tractor"},
    {c:"87084099",n:"变速箱其他未列名零件，用于拖拉机、10 人及以上载客机动车、轿车及其他主要设计用于载客的机动车、货运机动车及专用机动车（",e:"Parts for gear boxes for tractors, motor vehicles for the tr"},
    {c:"87087010",n:"车轮及其零附件，用于以下产品的工业装配：手扶拖拉机、轿车及其他主要设计用于载客的机动车、配备压燃式活塞内燃机（柴油或半柴",e:"Road wheels and parts and accessories thereof, for the indus"},
    {c:"87087050",n:"铝制车轮及其铝制零附件，用于拖拉机、10 人及以上载客机动车、轿车及其他主要设计用于载客的机动车、货运机动车及专用机动车",e:"Aluminium road wheels, aluminium parts and accessories there"},
    {c:"87087091",n:"星形轮辋，整体铸造，铸铁或钢制，用于拖拉机、10 人及以上载客机动车、轿车及其他主要设计用于载客的机动车、货运机动车及专",e:"Wheel centres in star form, cast in one piece, of iron or st"},
    {c:"87087099",n:"车轮及其其他未列名零附件，用于拖拉机、10 人及以上载客机动车、轿车及其他主要设计用于载客的机动车、货运机动车及专用机动",e:"Road wheels and parts and accessories thereof, for tractors,"},
    {c:"87088091",n:"悬挂系统及其零件，闭模锻钢制，用于拖拉机、10 人及以上载客机动车、轿车及其他主要设计用于载客的机动车、货运机动车及其他",e:"Suspension systems and parts thereof, of closed-die forged s"},
    {c:"87088099",n:"悬挂系统及其其他未列名零件，用于拖拉机、10 人及以上载客机动车、轿车及其他主要设计用于载客的机动车、货运机动车及专用机",e:"Suspension systems and parts thereof, for tractors, motor ve"},
    {c:"87088020",n:"悬挂系统及其零件（含减震器），用于以下产品的工业装配：轿车及其他主要设计用于载客的机动车、配备压燃式活塞内燃机（柴油或半",e:"Suspension systems and parts thereof, incl. shock-absorbers,"},
    {c:"87088035",n:"悬挂系统减震器，用于拖拉机、10 人及以上载客机动车、轿车及其他主要设计用于载客的机动车、货运机动车及专用机动车（不含子",e:"Suspension shock-absorbers for tractors, motor vehicles for "},
    {c:"87088055",n:"防侧倾杆和扭力杆，用于拖拉机、10 人及以上载客机动车、轿车及其他主要设计用于载客的机动车、货运机动车及专用机动车（不含",e:"Anti roll bars and torsion bars, for tractors, motor vehicle"},
    {c:"87089120",n:"散热器及其零件，用于以下产品的工业装配：手扶拖拉机、轿车及其他主要设计用于载客的机动车、配备压燃式活塞内燃机（柴油或半柴",e:"Radiators and parts thereof, for the industrial assembly of:"},
    {c:"87089135",n:"散热器，用于拖拉机、10 人及以上载客机动车、轿车及其他主要设计用于载客的机动车、货运机动车及专用机动车（不含子目 87",e:"Radiators for tractors, motor vehicles for the transport of "},
    {c:"87089191",n:"散热器零件，闭模锻钢制，用于拖拉机、10 人及以上载客机动车、轿车及其他主要设计用于载客的机动车、货运机动车及其他未列名",e:"Parts for radiators, of closed-die forged steel, for tractor"},
    {c:"87089199",n:"散热器其他未列名零件，用于拖拉机、10 人及以上载客机动车、轿车及其他主要设计用于载客的机动车、货运机动车及专用机动车（",e:"Parts for radiators, for tractors, motor vehicles for the tr"},
    {c:"87168000",n:"其他手推或手拉式车辆（含钢或铝）",e:"Other vehicles pushed or drawn by hand, containing steel or "},
    {c:"87169090",n:"挂车、半挂车及其他车辆的其他零件",e:"Other parts of trailers, semi-trailers and other vehicles"},
    {c:"90183210",n:"金属管状针",e:"Tubular metal needles"},
    {c:"90189075",n:"神经刺激设备（含钢或铝）",e:"Apparatus for nerve stimulation, containing steel or alumini"},
    {c:"90189084",n:"其他未列名仪器及设备（含钢或铝）",e:"Other instruments and appliances , containing steel or alumi"},
    {c:"90271090",n:"其他气体或烟雾分析设备（含钢或铝）",e:"Other gas or smoke analysis apparatus, containing steel or a"},
    {c:"94017900",n:"带金属框架的座椅",e:"Seats, with metal frames"},
    {c:"94031051",n:"带金属框架的办公桌",e:"Office desks, with metal frames"},
    {c:"94031098",n:"办公用金属家具，高度 > 80 厘米（不含品目 9017 的绘图专用桌、带门 / 百叶窗 / 挡板的橱柜及座椅）",e:"Metal furniture for offices, of > 80 cm in height (excl. tab"},
    {c:"94031058",n:"办公用金属家具，高度≤80 厘米（不含办公桌及品目 9017 的绘图专用桌）",e:"Metal furniture for offices, of <= 80 cm in height (excl. de"},
    {c:"94031091",n:"带门 / 百叶窗 / 挡板的金属橱柜，办公用，高度 > 80 厘米",e:"Metal cupboards with doors, shutters or flaps, for offices, "},
    {c:"94031093",n:"金属文件柜、卡片柜及其他橱柜，办公用，高度 > 80 厘米",e:"Metal filing, card-index and other cabinets, for offices, of"},
    {c:"94032020",n:"金属床（不含带机械装置的病床）（含钢或铝）",e:"Metal beds (excl. hospital beds with mechanical fittings), c"},
    {c:"94032080",n:"金属家具（不含办公用、医疗 / 外科 / 牙科 / 兽医用家具、床及座椅）（含钢或铝）",e:"Metal furniture (excl. for offices, medical, surgical, denta"},
    {c:"94069090",n:"预制建筑（含钢或铝）",e:"Prefabricated buildings, containing steel or aluminium"}
];

const cbamControlledPrefixes = ["2507", "2523", "2601", "2716", "2804", "2808", "2814", "2834", "3102", "3105", "7201", "7202", "7203", "7205", "7206", "7207", "7208", "7209", "7210", "7211", "7212", "7213", "7214", "7215", "7216", "7217", "7218", "7219", "7220", "7221", "7222", "7223", "7224", "7225", "7226", "7227", "7228", "7229", "7301", "7302", "7303", "7304", "7305", "7306", "7307", "7308", "7309", "7310", "7311", "7312", "7314", "7317", "7318", "7320", "7323", "7325", "7326", "7415", "7601", "7603", "7604", "7605", "7606", "7607", "7608", "7609", "7610", "7611", "7612", "7613", "7614", "7616", "8302", "8309", "8408", "8413", "8416", "8418", "8419", "8420", "8421", "8424", "8425", "8426", "8427", "8428", "8430", "8431", "8432", "8450", "8451", "8454", "8464", "8474", "8479", "8480", "8501", "8504", "8515", "8544", "8704", "8706", "8707", "8708", "8716", "9018", "9027", "9401", "9403", "9406"];

const cbamControlledCodes = cbamProductDB.map(function(item) { return item.c; });

function checkIsControlled(cnCode) {
    if (!cnCode) return false;
    cnCode = cnCode.replace(/\s/g, '').replace(/[^\d]/g, '');
    if (cnCode.length < 4) return false;
    var prefix4 = cnCode.substring(0, 4);
    if (cbamControlledPrefixes.indexOf(prefix4) === -1) return false;
    if (cnCode.length >= 8) {
        return cbamProductDB.some(function(item) { return item.c === cnCode.substring(0, 8); });
    }
    return cbamProductDB.some(function(item) { return item.c.indexOf(cnCode) === 0; });
}